import {useCallback,useEffect,useRef,useState} from 'react';
import {ArrowUpRight,ArrowRight,Download,Landmark,Activity,CalendarDays,Info,ExternalLink,Link as LinkIcon,Check} from 'lucide-react';
import {loadBundle,gdpAt,flowValue,total,cumulative,fiscalStart,fyLabel,shiftMonth,calendarAnniversary,operationEnd,fmt,bn,dateLabel,downloadCsv,isOverdue,type Bundle,type Mode,type Observation} from './data';
import {BudgetHistory} from './BudgetHistory';
import {DatePicker} from './DatePicker';
import {Card,ChartPanel,CompositionBars,DataTable,Disclosure,SourceLine,type ChartRow} from './components';

const monthNames=['Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec','Jan','Feb','Mar'];
function useParam(key:string,fallback:string){
 const [value,setValue]=useState(()=>new URLSearchParams(location.search).get(key)||fallback);
 useEffect(()=>{const update=()=>setValue(new URLSearchParams(location.search).get(key)||fallback);window.addEventListener('popstate',update);return()=>window.removeEventListener('popstate',update);},[key,fallback]);
 const update=(v:string)=>{const url=new URL(location.href);url.searchParams.set(key,v);history.pushState({},'',url);setValue(v);};return [value,update] as const;
}
function Select({label,value,onChange,options}:{label:string;value:string;onChange:(s:string)=>void;options:{value:string;label:string}[]}){return <label className="select-label"><span>{label}</span><select aria-label={label} value={value} onChange={e=>onChange(e.target.value)}>{options.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select></label>;}
function changeText(current:number|null,previous:number|null,percent=false){if(current==null||previous==null)return 'Prior-year comparison unavailable';const delta=current-previous;if(percent&&previous>0)return `${delta>=0?'+':'−'}${fmt(Math.abs(delta)/previous*100)}% versus same period last year`;return `${bn(Math.abs(delta))} ${delta>=0?'more':'less'} than same period last year`;}
function DataStatus({bundle}:{bundle:Bundle}){
 const {manifest,fiscal,debt,composition,curve}=bundle;
 const curveDate=curve.asOf||curve.observationDate;
 const ages=[['fiscal',fiscal.asOf],['debt',debt.asOf],['composition',composition.asOf],...(curveDate?[['curve',curveDate]]:[])].filter(([group,date])=>isOverdue(group,date)).map(([group])=>group);
 const failed=Object.entries(manifest?.groups||{}).filter(([,v])=>v.status==='failed').map(([k])=>k);
 return <>{(ages.length>0||failed.length>0)&&<div className="notice" role="status"><Info size={18}/><span>{ages.length>0?`Some observations may be overdue: ${ages.join(', ')}. `:''}{failed.length>0?`Latest refresh could not update ${failed.join(', ')}. `:''}Showing the last saved data; check the source dates below.</span></div>}</>;
}

function FiscalPage({bundle}:{bundle:Bundle}){
 const {fiscal,forecast,composition}=bundle;const obs=fiscal.observations;const last=obs.at(-1)!;const end=last.date;const year=fiscalStart(end);
 const [modeParam,setMode]=useParam('period','ytd');const mode:Mode=['ytd','month','rolling'].includes(modeParam)?modeParam as Mode:'ytd';
 const [unitsParam,setUnits]=useParam('units','bn');const units=unitsParam==='gdp'?'gdp':'bn';const unit=units==='gdp'?'% of GDP':'£bn';
 const scale=(v:number|null,date:string)=>flowValue(v,date,units,fiscal.gdp);
 const showFlow=(v:number|null,date:string)=>{const n=scale(v,date);return n==null?'Not available':units==='gdp'?`${fmt(n,2)}%`:bn(v);};
 const denominator=gdpAt(fiscal.gdp,end);
 const gdpNote=units==='gdp'?`Flows divided by the latest four-quarter nominal GDP ending on or before each flow endpoint (maximum two-month gap). Monthly and YTD flows are not annualised. Dashboard scaling, not the official ONS fiscal ratio.`:'';
 const flowSources=[...fiscal.sources,...(units==='gdp'?(fiscal.gdp?.sources||[]):[])];
 const [range,setRange]=useParam('history','5y');const [receipt,setReceipt]=useParam('receipt','incomeTax');const [spend,setSpend]=useParam('spend','goodsServices');const [annualParam,setAnnual]=useParam('year',composition.asOf);
 const [compositionUnitParam,setCompositionUnits]=useParam('compositionUnits','share');const compositionUnits=compositionUnitParam==='gdp'?'gdp':'share';
 const annual=composition.years.find(y=>y.year===annualParam)||composition.years.at(-1)!;
 const receiptKeys=['incomeTax','nic','vat','corporationTax'];const spendKeys=['goodsServices','benefits','interest','netInvestment','currentSpending'];
 const receiptKey=receiptKeys.includes(receipt)?receipt:'incomeTax';const spendKey=spendKeys.includes(spend)?spend:'goodsServices';
 const modeLabel=mode==='ytd'?`April–${dateLabel(end).split(' ')[0]} ${year}`:mode==='month'?dateLabel(end):`12 months to ${dateLabel(end)}`;
 const current=(key:string)=>total(obs,key,end,mode);const previous=(key:string)=>total(obs,key,shiftMonth(end,-12),mode);
 const curr=cumulative(obs,year),prev=cumulative(obs,year-1);
 const profile=forecast.status==='available'&&forecast.fiscalYear===`${year}-${String(year+1).slice(-2)}`?forecast.cumulative:undefined;
 const gdpFields=(date:string,prefix='')=>{const d=gdpAt(fiscal.gdp,date);return {[`${prefix}gdpEnd`]:d?.date??null,[`${prefix}gdpBn`]:d?.rollingAnnualMillion==null?null:d.rollingAnnualMillion/1000};};
 const gdpColumns=units==='gdp'?[{key:'gdpEnd',label:'GDP four-quarter end'},{key:'gdpBn',label:'GDP denominator (£bn)'}]:[];
 const borrowRows:ChartRow[]=monthNames.map((label,i)=>{const date=shiftMonth(`${year}-04`,i),old=shiftMonth(date,-12);const forecastValue=profile?.find(p=>p.period===date)?.value;return {label,...gdpFields(date),...gdpFields(old,'previous'),current:scale(curr[i],date),previous:scale(prev[i],old),forecast:forecastValue==null||(units==='gdp'&&date>end)?null:scale(forecastValue*1000,date)};});
 const ytd=total(obs,'borrowing',end,'ytd')!;const forecastToDate=profile?.find(p=>p.period===end)?.value;const diff=forecastToDate===undefined?null:ytd/1000-forecastToDate;
 const scaledGap=diff===null?null:scale(Math.abs(diff)*1000,end);const gapText=scaledGap==null?'Comparison unavailable':units==='gdp'?`${fmt(scaledGap,2)}pp`:`£${fmt(scaledGap)}bn`;
 const summary=`April to ${dateLabel(end)}: ${showFlow(ytd,end)}. ${diff!==null&&scaledGap!==null?`${gapText} ${diff>=0?'above':'below'} the OBR profile.`:'Compare with the same period last year.'}`;
 const oldDebt=obs.find(r=>r.date===shiftMonth(end,-12));
 const history=obs.filter(r=>(range==='all'||r.date>=shiftMonth(end,-59))&&(mode!=='ytd'||r.date.slice(5)===end.slice(5)));
 const flowRows=history.map(r=>({label:dateLabel(r.date,true),...gdpFields(r.date),receipts:scale(total(obs,'receipts',r.date,mode),r.date),spending:scale(total(obs,'spending',r.date,mode),r.date)}));
 const categoryRows=(key:string)=>history.map(r=>({label:dateLabel(r.date,true),...gdpFields(r.date),value:scale(total(obs,key,r.date,mode),r.date)}));
 const flowChange=(key:string,percent=false)=>{if(units!=='gdp')return changeText(current(key),previous(key),percent);const a=scale(current(key),end),b=scale(previous(key),shiftMonth(end,-12));return a==null||b==null?'Prior-year GDP comparison unavailable':`${a-b>=0?'+':'−'}${fmt(Math.abs(a-b),2)}pp versus same period last year`;};
 const revenueYear=Number(annual.year.slice(0,4));const revenueEnd=`${revenueYear+1}-03`;
 // Economic receipt groups would not distinguish the major taxes. Show selected central-government taxes separately and a clearly named residual to the all-public-sector total.
 const revenueTotal=total(obs,'receipts',revenueEnd,'ytd');
 const revenueItems=receiptKeys.map(key=>({name:fiscal.series[key].label,value:total(obs,key,revenueEnd,'ytd')}));
 const validRevenue=revenueTotal!==null&&revenueItems.every(x=>x.value!==null);
 const compositionGdp=gdpAt(fiscal.gdp,revenueEnd);const compositionGdpValue=compositionGdp?.date===revenueEnd?compositionGdp.rollingAnnualMillion:null;
 const compositionGdpNote=`four-quarter GDP for April–March ${annual.year}, ONS BKTL (latest saved vintage). Dashboard scaling, not Treasury published GDP shares`;
 const compositionGdpSources=compositionUnits==='gdp'?(fiscal.gdp?.sources||[]):[];
 return <>
  <div className="page-heading"><div><p className="eyebrow">PUBLIC FINANCES · {dateLabel(end).toUpperCase()}</p><h1>The UK’s fiscal position.</h1><p className="intro">The latest borrowing picture, its drivers, and the forecast it is measured against.</p></div><div className="release-stamp"><span className="status-dot"/>ONS release <strong>{dateLabel(fiscal.releaseDate,true)}</strong></div></div>
  <div className="toolbar"><div className="segmented" aria-label="Headline and flow chart period">{([{id:'ytd',label:'Financial year to date'},{id:'month',label:'Latest month'},{id:'rolling',label:'Rolling 12 months'}] as const).map(x=><button key={x.id} aria-pressed={mode===x.id} onClick={()=>setMode(x.id)}>{x.label}</button>)}</div><Select label="Flow units" value={units} onChange={setUnits} options={[{value:'bn',label:'£bn'},{value:'gdp',label:'% of GDP'}]}/><span className="period-caption">{modeLabel}</span></div>{units==='gdp'&&<p className="basis-note">{denominator?`Headline denominator: £${fmt(denominator.rollingAnnualMillion!/1000)}bn nominal GDP, four quarters ending ${dateLabel(denominator.date)}.`:'No sufficiently recent GDP denominator is available for the headline period.'} Monthly and YTD flows are not annualised. Each historical point uses its own available denominator; these are dashboard ratios, not official ONS fiscal ratios.</p>}
  <div className="metrics"><Card label="Net borrowing" value={showFlow(current('borrowing'),end)} detail={flowChange('borrowing')} highlight/><Card label="Current receipts" value={showFlow(current('receipts'),end)} detail={flowChange('receipts',true)}/><Card label="Total spending" value={showFlow(current('spending'),end)} detail={flowChange('spending',true)}/><Card label="Net debt / GDP" value={`${fmt(Number(last.debtPct))}%`} detail={`${dateLabel(end,true)} stock · ${oldDebt?`${fmt(Number(last.debtPct)-Number(oldDebt.debtPct))}pp versus a year ago`:'prior year unavailable'}`}/></div>
  <div className="briefing"><span className="briefing-label">IN FOCUS</span><p>{diff!==null&&scaledGap!==null?<>Borrowing is <strong>{gapText} {diff>=0?'above':'below'}</strong> the {forecast.vintage} OBR profile in the financial year to {dateLabel(end)}.</>:<>Borrowing in the financial year to {dateLabel(end)} is <strong>{showFlow(ytd,end)}</strong>. A comparison on this basis is unavailable.</>} <span className="muted">Early estimates can be revised.</span></p></div>
  <ChartPanel id="borrowing" title="Borrowing against the forecast" subtitle={`Cumulative borrowing · financial year ${fyLabel(year)} · ${unit}`} summary={summary} unit={unit} extraColumns={units==='gdp'?[...gdpColumns,{key:'previousgdpEnd',label:'Prior-year GDP four-quarter end'},{key:'previousgdpBn',label:'Prior-year GDP denominator (£bn)'}]:[]} rows={borrowRows} lines={[{key:'current',label:`${fyLabel(year)} outturn`},{key:'previous',label:`${fyLabel(year-1)} outturn`,colour:'#829097'},...(profile?[{key:'forecast',label:`OBR · ${forecast.vintage}`,colour:'#b47936',dash:'6 5'}]:[])]} sources={[...flowSources,...(profile?forecast.sources:[])]} note={`Public sector excluding banks. Positive = borrowing; negative = surplus. Outturn vintage ${fiscal.releaseDate}; forecast rounded to £0.1bn. This chart always shows financial-year cumulative flows. ${gdpNote} ${units==='gdp'?'Forecast percentages stop at the latest outturn month; no GDP forecast is assumed.':''}`}/>
  <div className="section-header"><div><p className="eyebrow">UNDER THE HEADLINE</p><h2>Where the change comes from</h2></div><Select label="History" value={range} onChange={setRange} options={[{value:'5y',label:'Last 5 years'},{value:'all',label:'Since April 2000'}]}/></div>
  <ChartPanel id="flows" title="Receipts and spending" subtitle={`${mode==='rolling'?'Rolling 12-month':mode==='ytd'?`April–${dateLabel(end).split(' ')[0]} totals in each financial year`:'Monthly'} flows · ${unit}`} summary="The gap between total managed expenditure and current receipts is net borrowing. Both series use the same public-sector coverage." unit={unit} extraColumns={gdpColumns} rows={flowRows} lines={[{key:'receipts',label:'Current receipts'},{key:'spending',label:'Total managed expenditure',colour:'#b47936'}]} sources={flowSources} note={`${fiscal.basis}. ${gdpNote} ${mode==='ytd'?'Every year uses the same April-to-latest-month coverage, not a full-year total.':''}`}/>
  <Disclosure title="Explore receipts" subtitle="Income tax, National Insurance, VAT and corporation tax"><Select label="Receipt series" value={receiptKey} onChange={setReceipt} options={receiptKeys.map(k=>({value:k,label:fiscal.series[k].label}))}/><ChartPanel id="receipt-detail" title={fiscal.series[receiptKey].label} subtitle={`${modeLabel} comparison basis · historical ${mode} values · ${unit}`} summary="Selected central-government tax receipts on the ONS accrual basis. These lines are not an exhaustive breakdown of all public receipts." unit={unit} extraColumns={gdpColumns} rows={categoryRows(receiptKey)} lines={[{key:'value',label:fiscal.series[receiptKey].label}]} sources={flowSources} note={`${gdpNote} ONS ${fiscal.series[receiptKey].code} · ${fiscal.series[receiptKey].scope}. ${receiptKey==='corporationTax'?'Gross of tax credits; do not compare directly with HMRC cash receipts.':''}`}/></Disclosure>
  <Disclosure title="Explore spending" subtitle="Goods and services, benefits, interest and investment"><Select label="Spending series" value={spendKey} onChange={setSpend} options={spendKeys.map(k=>({value:k,label:fiscal.series[k].label}))}/><ChartPanel id="spending-detail" title={fiscal.series[spendKey].label} subtitle={`Historical ${mode} values · ${unit}`} summary="Economic categories show how spending is recorded. The annual functional view below shows what services it supports." unit={unit} extraColumns={gdpColumns} rows={categoryRows(spendKey)} lines={[{key:'value',label:fiscal.series[spendKey].label}]} sources={flowSources} note={`${gdpNote} ONS ${fiscal.series[spendKey].code} · ${fiscal.series[spendKey].scope}. Categories overlap with current expenditure; do not add all menu options together.`}/></Disclosure>
  <BudgetHistory fiscal={fiscal} functional={composition.history}/>
  <Disclosure title="The composition of the state" subtitle="Annual spending by function and the main revenue sources"><div className="section-header"><p className="small">A complete financial-year snapshot, not an estimate of steady state.</p><Select label="Composition units" value={compositionUnits} onChange={setCompositionUnits} options={[{value:'share',label:'% of named total'},{value:'gdp',label:'% of GDP'}]}/><Select label="Composition year" value={annual.year} onChange={setAnnual} options={[...composition.years].reverse().map(y=>({value:y.year,label:y.year}))}/></div><div className="composition-grid"><CompositionBars title="Spending by function" units={compositionUnits} gdp={compositionGdpValue} gdpNote={compositionGdpNote} totalName="Public-sector expenditure on services (TES)" items={annual.items} total={annual.total} source={[...composition.sources,...compositionGdpSources]} metadata={`${annual.year} · Treasury PESA 2026 table 5.2. ${composition.basis}`}/>{validRevenue&&<CompositionBars title="Revenue sources" units={compositionUnits} gdp={compositionGdpValue} gdpNote={compositionGdpNote} totalName="Public-sector current receipts" items={[...revenueItems.map(x=>({name:x.name,value:x.value!})),{name:'Other receipts & accounting differences',value:revenueTotal!-revenueItems.reduce((s,x)=>s+x.value!,0)}]} total={revenueTotal!} source={[...fiscal.sources,...compositionGdpSources]} metadata={`${annual.year} · Selected central-government taxes plus residual to all-public-sector current receipts. Corporation tax is gross of tax credits; residual includes other taxes, non-tax receipts and accounting differences. ONS ${fiscal.releaseDate} vintage.`}/>}</div></Disclosure>
  <Disclosure title="Sources, definitions and release calendar" subtitle={`Next ONS release: ${fiscal.nextRelease}`}><ul className="notes-list">{fiscal.notes.map(n=><li key={n}>{n}</li>)}</ul><SourceLine sources={fiscal.sources}/><p className="small">Annual spending history covers the five comparable years in PESA 2026. Refreshing preserves release vintages; the app currently displays the latest saved vintage.</p></Disclosure>
 </>;
}

function DebtPage({bundle}:{bundle:Bundle}){
 const {debt,fiscal}=bundle;const last=fiscal.observations.at(-1)!;const [horizon,setHorizon]=useParam('maturity','all');const [search,setSearch]=useState('');
 const currentDate=new Date().toISOString().slice(0,10);const calendar=debt.calendar.filter(e=>operationEnd(e)>=currentDate).sort((a,b)=>a.date.localeCompare(b.date));
 const next=calendar[0];const maturities=debt.securities.filter(s=>s.maturityDate>=currentDate&&s.maturityDate<=calendarAnniversary(currentDate));
 const grouped:Record<string,ChartRow>={};for(const s of debt.securities){const y=fiscalStart(s.maturityDate);const key=fyLabel(y);const r=grouped[key]||{label:key,conventional:0,linked:0};r[s.type==='conventional'?'conventional':'linked']=Number(r[s.type==='conventional'?'conventional':'linked'])+s.nominalMillion/1000;grouped[key]=r;}
 const maturityRows=Object.values(grouped).filter(r=>horizon==='all'||Number(String(r.label).slice(0,4))<fiscalStart(debt.asOf)+10);
 const linked=debt.securities.filter(s=>s.type==='index-linked').reduce((s,r)=>s+r.nominalMillion,0);
 const avg=debt.securities.reduce((sum,s)=>sum+s.nominalMillion*(new Date(s.maturityDate).getTime()-new Date(debt.asOf).getTime())/86400000/365.25,0)/debt.totals.nominalMillion;
 const stockSource=debt.sources.slice(0,1);const filtered=debt.securities.filter(s=>`${s.name} ${s.isin}`.toLowerCase().includes(search.toLowerCase()));
 const debtMeta=`DMO snapshot ${debt.asOf}; nominal principal £ million; index-linked principal excludes inflation uplift. Not public sector net debt. ${stockSource.map(s=>s.url).join(' ')}`;
 return <><div className="page-heading"><div><p className="eyebrow">DEBT MANAGEMENT · {dateLabel(debt.asOf,true).toUpperCase()}</p><h1>The stock. The cost. The calendar.</h1><p className="intro">Outstanding gilts, refinancing needs and the latest published financing operations.</p></div><div className="release-stamp"><Landmark size={16}/>DMO stock <strong>{dateLabel(debt.asOf,true)}</strong></div></div>
  <div className="metrics"><Card label="Gilts outstanding · face value" value={bn(debt.totals.nominalMillion)} detail={`Nominal principal · ${dateLabel(debt.asOf,true)}`} highlight/><Card label="Index-linked share" value={`${fmt(linked/debt.totals.nominalMillion*100)}%`} detail="Share of nominal principal, before inflation uplift"/><Card label="Average remaining maturity" value={`${fmt(avg)} years`} detail="Principal-weighted contractual maturity; not duration"/><Card label="Public sector net debt" value={`£${fmt(Number(last.debtBillion))}bn`} detail={`${dateLabel(last.date,true)} · ${fmt(Number(last.debtPct))}% of GDP · ONS`}/></div>
  <p className="basis-note"><Info size={16}/>Gilt face value and public sector net debt measure different things. Including current indexation uplift, the DMO gilt stock is {bn(debt.totals.upliftedMillion)}.</p>
  <div className="two-column"><ChartPanel id="maturities" title="When gilts mature" subtitle="Nominal principal by financial year · £bn" summary="Redemption concentration across the outstanding stock. Index-linked amounts exclude future and accumulated inflation uplift; this is not a cash-payment forecast." rows={maturityRows} bars lines={[{key:'conventional',label:'Conventional',colour:'#4E79A7'},{key:'linked',label:'Index-linked',colour:'#F28E2B'}]} sources={stockSource} note={`Stock at ${debt.asOf}. Original nominal principal, including government holdings.`}><Select label="Maturity horizon" value={horizon} onChange={setHorizon} options={[{value:'all',label:'Full maturity profile'},{value:'10',label:'Next 10 financial years'}]}/></ChartPanel>
  <section className="panel next-operation"><p className="eyebrow">NEXT PUBLISHED OPERATION</p>{next?<><CalendarDays size={26}/><h2>{dateLabel(next.date)}</h2><span className="tag">{next.datePrecision?.startsWith('week')?'Week commencing · ':''}{next.type}</span><h3>{next.name}</h3><p className="next-amount">{next.amountMillion!=null?bn(next.amountMillion):'Size not yet announced'}</p><p className="small">{next.status}</p><a className="text-link" href={next.sourceUrl} target="_blank" rel="noreferrer">Read the official notice <ArrowUpRight size={15}/></a></>:<><h2>No future operation in the saved calendar</h2><p>Check the DMO for new announcements.</p></>}<div className="card-footnote">Calendar is based on published notices. Dates and amounts can change; this is a saved snapshot.</div></section></div>

  <div className="section-header"><div><p className="eyebrow">ROLLING ON & ROLLING OFF</p><h2>The financing calendar</h2></div></div>
  <section className="panel"><div className="panel-heading"><div><h2>Upcoming sales</h2><p>Published auctions, tenders and syndication windows</p></div><button className="plain-button" onClick={()=>downloadCsv('upcoming-operations',['Date','Date precision','Type','Gilt','Amount (£ million)','Status','Notice URL'],calendar.map(e=>[e.date,e.datePrecision,e.type,e.name,e.amountMillion,e.status,e.sourceUrl]),`DMO calendar snapshot. ${JSON.stringify(debt.availability.calendar)}`)}><Download size={16}/> CSV</button></div><p className="small">Pinned quarterly notices; verify changes with the DMO. A syndication week is a window, not a confirmed auction day.</p><DataTable caption="Upcoming gilt operations" headers={['Date / window','Operation','Gilt / maturity','Announced size','Status']} rows={calendar.map(e=>[<a href={e.sourceUrl} target="_blank" rel="noreferrer">{e.datePrecision?.startsWith('week')?'w/c ':''}{dateLabel(e.date,true)}</a>,e.type,e.name,e.amountMillion==null?'Not announced':bn(e.amountMillion),e.status])}/></section>
  <Disclosure title="Redemptions in the next 12 months" subtitle={`${maturities.length} gilts · nominal principal, before linker inflation uplift`}><DataTable caption="Upcoming gilt redemptions" headers={['Maturity date','Gilt','ISIN','Nominal principal']} rows={maturities.map(s=>[dateLabel(s.maturityDate,true),s.name,s.isin,bn(s.nominalMillion)])}/><button className="plain-button" onClick={()=>downloadCsv('redemptions',['Date','Gilt','ISIN','Nominal £ million'],maturities.map(s=>[s.maturityDate,s.name,s.isin,s.nominalMillion]),debtMeta)}><Download size={16}/> CSV</button><SourceLine sources={stockSource}/></Disclosure>
  <Disclosure title="Recent auction results" subtitle={`${debt.auctions.length} published results · demand, yields and post-auction take-up`}><p className="small">Coverage: {typeof debt.availability.auctions==='object'?JSON.stringify(debt.availability.auctions):String(debt.availability.auctions)}. Conventional yields are nominal; index-linked yields are real. “—” means not published or not applicable.</p><DataTable caption="Recent gilt auction results" headers={['Auction','Gilt','Allotted £bn','Yield %','Cover ×','Tail bp','Post-auction £bn']} rows={[...debt.auctions].sort((a,b)=>b.date.localeCompare(a.date)).map(a=>[a.sourceUrl?<a href={a.sourceUrl} target="_blank" rel="noreferrer">{dateLabel(a.date,true)}</a>:dateLabel(a.date,true),a.name,a.allottedMillion==null?'—':fmt(a.allottedMillion/1000,2),a.yieldPct==null?'—':fmt(a.yieldPct,3),a.cover==null?'—':fmt(a.cover,2),a.tailBp==null?'—':fmt(a.tailBp,1),a.postAuctionMillion==null?'—':fmt(a.postAuctionMillion/1000,3)])}/><button className="plain-button" onClick={()=>downloadCsv('auction-results',['Date','Gilt','Offered £ million','Allotted £ million','Accepted yield %','Cover','Tail bp','Post-auction £ million','Notice URL'],debt.auctions.map(a=>[a.date,a.name,a.offeredMillion,a.allottedMillion,a.yieldPct,a.cover,a.tailBp,a.postAuctionMillion,a.sourceUrl]),'DMO. Index-linked yields are real, conventional yields nominal. Tail is weighted-average versus lowest accepted price yield; not a when-issued comparison. Post-auction is separate from the initial allotment.')}><Download size={16}/> CSV</button></Disclosure>
  <Disclosure title="Explore the gilt stock" subtitle={`${debt.securities.length} outstanding securities · coupons, maturity and principal`}><label className="search-label">Find a gilt<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search by name, year or ISIN"/></label><p className="small" role="status">{filtered.length} matching securities</p><DataTable caption="Gilts outstanding" headers={['Gilt','ISIN','Coupon %','Maturity','Nominal £bn','With current uplift £bn']} rows={filtered.map(s=>[s.name,s.isin,fmt(s.couponPct,3),dateLabel(s.maturityDate,true),fmt(s.nominalMillion/1000,2),fmt(s.upliftedMillion/1000,2)])}/><button className="plain-button" onClick={()=>downloadCsv('gilt-stock',['Gilt','ISIN','Type','Coupon %','Maturity','Nominal £ million','Including current uplift £ million'],filtered.map(s=>[s.name,s.isin,s.type,s.couponPct,s.maturityDate,s.nominalMillion,s.upliftedMillion]),debtMeta)}><Download size={16}/> CSV</button><SourceLine sources={stockSource} note="Coupons are contractual rates, not current market yields. Uplifted principal is not market value."/></Disclosure>
 </>;
}

function PricingPage({bundle,onReload,reloading}:{bundle:Bundle;onReload:()=>void;reloading:boolean}){
 const {curve}=bundle;
 const dates=curve.curves.map(c=>c.date).sort().reverse();
 const [dateParam,setDate]=useParam('pricingDate',dates[0]||'');
 const selected=dates.includes(dateParam)?dateParam:dates[0];
 const [compareParam,setCompare]=useParam('pricingCompare',dates[1]||dates[0]||'');
 const comparison=dates.includes(compareParam)?compareParam:dates[1]||selected;
 const dateControls=(prefix='')=><div className="pricing-controls"><DatePicker label={prefix?`${prefix}: observation date`:'Observation date'} value={selected} onChange={setDate} dates={dates}/><DatePicker label={prefix?`${prefix}: compare with`:'Compare with'} value={comparison} onChange={setCompare} dates={dates}/></div>;
 const incomplete=!curve.realCurves?.length||!curve.breakevenCurves?.length;
 const datasets=[{id:'yield-curve',title:'Nominal gilt yield curve',data:curve.curves,description:'Fitted nominal zero-coupon spot yields. Market yields are not coupons payable on the existing debt stock.'},{id:'real-curve',title:'Real gilt yield curve',data:curve.realCurves||[],description:'Fitted real zero-coupon spot yields from RPI-linked gilts.'},{id:'breakeven',title:'RPI breakeven inflation',data:curve.breakevenCurves||[],description:'Matched nominal minus real spot yields: annualised RPI inflation compensation over each horizon. Includes inflation risk and relative liquidity premia; not a pure inflation forecast.'}];
 return <><div className="page-heading"><div><p className="eyebrow">MARKET PRICING · UK GILTS</p><h1>Yields and inflation pricing.</h1><p className="intro">Compare the term structure across dates and inspect the change at each maturity.</p></div><button onClick={onReload} disabled={reloading}>{reloading?'Reloading…':'Reload saved data'}</button></div>{incomplete&&dates.length>0&&<p className="notice" role="status">This snapshot contains nominal yields but is missing real yields or RPI breakevens. Reload saved data to pick up a newer snapshot. If it remains incomplete, run the documented curve refresh.</p>}
 {dates.length?<>{dateControls()}<p className="small">Choose any two saved observation dates above, on the RPI breakeven chart, or inside a change panel; the selection updates all three curves. Changes are observation date minus comparison date. Rates are continuously compounded, in % per annum; changes are basis points.</p>
 {datasets.map(dataset=>{const current=dataset.data.find(c=>c.date===selected);const previous=dataset.data.find(c=>c.date===comparison);const rows:ChartRow[]=(current?.points||[]).map(p=>{const old=previous?.points.find(q=>q.tenor===p.tenor)?.rate??null;return {tenor:p.tenor,current:p.rate,comparison:old,change:p.rate==null||old==null?null:(p.rate-old)*100};});return current?<div key={dataset.id}><ChartPanel id={dataset.id} title={dataset.title} subtitle={`${dateLabel(selected,true)} versus ${dateLabel(comparison,true)} · % per annum`} summary={dataset.description} rows={rows} xKey="tenor" xLabel="Maturity (years)" unit="%" zero={false} lines={[{key:'current',label:dateLabel(selected,true)},...(previous?[{key:'comparison',label:dateLabel(comparison,true),colour:'#829097',dash:'5 4'}]:[])]} sources={curve.sources} note="Bank of England fitted spot curves, continuously compounded. Only matching published dates and tenors are compared; missing observations are not interpolated.">{dataset.id==='breakeven'&&dateControls('RPI breakeven')}</ChartPanel>{previous?<Disclosure title={`${dataset.title}: change in basis points`} subtitle={`${dateLabel(selected,true)} minus ${dateLabel(comparison,true)}`}>{dateControls(dataset.title)}<ChartPanel id={`${dataset.id}-change`} title={`${dataset.title} change`} subtitle={`${dateLabel(selected,true)} minus ${dateLabel(comparison,true)} · basis points`} summary="A positive value means the rate increased between the selected dates. 100 basis points = 1 percentage point." rows={rows} xKey="tenor" xLabel="Maturity (years)" unit="bp" lines={[{key:'change',label:'Change'}]} sources={curve.sources}/></Disclosure>:<p className="small">No matching comparison-date curve is available.</p>}</div>:<section className="panel unavailable" key={dataset.id}><h2>{dataset.title}</h2><p>No verified curve is available for this date. Refresh the local curve data or choose another date.</p></section>;})}
 </>:<section className="panel unavailable"><h2>Yield curves unavailable</h2><p>No verified yield-curve snapshot is saved on this device. Run the curve refresh to download the official data.</p></section>}
 <Disclosure title="How to read these curves" subtitle="Spot rates, inflation compensation and data coverage"><p className="small">A ten-year spot breakeven measures annualised inflation compensation over the next ten years, not inflation in year ten. Subtracting comparable continuously compounded nominal and real spot rates produces a continuously compounded breakeven. This is RPI-linked pricing, not CPI inflation expectations. Indexation conventions, the RPI methodology change from 2030, risk premia and market liquidity matter when interpreting the curve.</p><ul className="notes-list">{curve.notes?.map(n=><li key={n}>{n}</li>)}</ul><SourceLine sources={curve.sources}/></Disclosure>
 </>;
}

export default function App(){
 const [bundle,setBundle]=useState<Bundle|null>(null);const [error,setError]=useState('');const [page,setPage]=useParam('page','fiscal');const [copied,setCopied]=useState(false);const [copyStatus,setCopyStatus]=useState('');
 const [reloading,setReloading]=useState(false);const inFlight=useRef(false);const savedBundle=useRef<Bundle|null>(null);
 const reload=useCallback(async()=>{if(inFlight.current)return;inFlight.current=true;setReloading(true);try{const next=await loadBundle(savedBundle.current||undefined);savedBundle.current=next;setBundle(next);setError(next.loadWarnings?.join(' ')||'');}catch(e){setError(e instanceof Error?e.message:String(e));}finally{inFlight.current=false;setReloading(false);}},[]);
 useEffect(()=>{void reload();const focus=()=>{void reload();};const visible=()=>{if(document.visibilityState==='visible')void reload();};window.addEventListener('focus',focus);document.addEventListener('visibilitychange',visible);return()=>{window.removeEventListener('focus',focus);document.removeEventListener('visibilitychange',visible);};},[reload]);
 const active=page==='debt'?'debt':page==='pricing'?'pricing':'fiscal';
 async function copy(){try{await navigator.clipboard.writeText(location.href);setCopied(true);setCopyStatus('Link copied.');setTimeout(()=>setCopied(false),2000);}catch{setCopied(false);setCopyStatus('Copy was unavailable. Copy the address from your browser instead.');}}
 return <><a className="skip-link" href="#main">Skip to content</a><header className="site-header"><div className="header-inner"><a className="brand" href="?page=fiscal"><span className="brand-mark"><Landmark size={21}/></span><span>UK <strong>Fiscal</strong><small>POLICY DASHBOARD</small></span></a><nav aria-label="Dashboard pages"><button className={active==='fiscal'?'active':''} aria-current={active==='fiscal'?'page':undefined} onClick={()=>setPage('fiscal')}><Activity size={16}/>Fiscal position</button><button className={active==='debt'?'active':''} aria-current={active==='debt'?'page':undefined} onClick={()=>setPage('debt')}><Landmark size={16}/>Debt & financing</button><button className={active==='pricing'?'active':''} aria-current={active==='pricing'?'page':undefined} onClick={()=>setPage('pricing')}><Activity size={16}/>Pricing</button></nav><button className="share-button" onClick={copy} aria-label="Copy link to this view">{copied?<Check size={16}/>:<LinkIcon size={16}/>}<span>{copied?'Copied':'Copy view link'}</span></button></div></header><main id="main" className="page-shell"><p className={copyStatus.startsWith('Copy was')?'notice':'sr-only'} role="status" aria-live="polite">{copyStatus}</p>{error&&!bundle?<section className="panel error" role="alert"><h1>The saved data could not be loaded.</h1><p>{error}</p><p>Run the documented refresh command, then reload this page.</p><button onClick={()=>location.reload()}>Try again</button></section>:bundle?<>{error&&<p className="notice" role="status">Some saved data could not be loaded. Keeping previously loaded data where available. {error}</p>}<DataStatus bundle={bundle}/>{active==='fiscal'?<FiscalPage bundle={bundle}/>:active==='debt'?<DebtPage bundle={bundle}/>:<PricingPage bundle={bundle} onReload={()=>void reload()} reloading={reloading}/>}<footer><div><strong>UK Fiscal</strong><p>An independent briefing tool by Patrick Schneider.<br/>Official data; independent presentation.</p></div><div><a href="https://github.com/patrickmschneider/uk-fiscal" target="_blank" rel="noreferrer">Project & methodology <ArrowUpRight size={14}/></a><p>{bundle.manifest?`Last refresh attempt: ${new Date(bundle.manifest.generatedAt).toLocaleString('en-GB')}`:'Saved data snapshot · manual refresh'}<br/>Observation and publication dates are shown per source.</p></div></footer></>:<section className="loading" role="status"><p className="eyebrow">UK FISCAL</p><h1>Loading the latest saved picture.</h1><p>Reading the validated data snapshot…</p></section>}</main></>;
}
