import {useState} from 'react';
import {ChartPanel,DataTable,Disclosure,type ChartRow} from './components';
import {annualBudgets,budgetValue,type BudgetYear,type FunctionalHistory} from './budgetMath';
import {dateLabel,downloadCsv,fmt,gdpAt,total,type Fiscal,type Source} from './data';

const palette=['#17685a','#b47936','#687d96','#805d77','#64764b','#84634f','#3d7880','#625c94','#95606a','#6b7161','#4c666f','#73645e'];
export function BudgetHistory({fiscal,functional}:{fiscal:Fiscal;functional?:FunctionalHistory}){
 const [view,setView]=useState('economic');const [units,setUnits]=useState('gdp');const [from,setFrom]=useState('2019-20');const [to,setTo]=useState('');
 const years:BudgetYear[]=view==='functional'?(functional?.years||[]):annualBudgets(fiscal,view==='receipts'?'receipts':'economic');
 const first=years.find(y=>y.year===from)||years[0],last=years.find(y=>y.year===to)||years.at(-1);
 const sources:Source[]=view==='functional'?(functional?.sources||[]):[...fiscal.sources,...(fiscal.gdp?.sources||[])];
 const unit=units==='gdp'?'% of GDP':units==='share'?'% of total':'£bn';
 const title=view==='receipts'?'Revenue composition over time':view==='functional'?'Spending by function over time':'Spending by economic category over time';
 const names=[...new Set(years.flatMap(y=>y.items.map(i=>i.name)))];
 const rows:ChartRow[]=years.map(y=>({label:y.year,...Object.fromEntries(names.map((name,i)=>{const item=y.items.find(x=>x.name===name);return [`v${i}`,item?budgetValue(item.value,item.pctGdp,y.total,units):null];}))}));
 const note=view==='functional'?`${functional?.basis}. Categories sum to expenditure on services (TES), not total managed expenditure (TME). Social protection includes pensions and social services; it is not just working-age benefits. Debt interest is included within general public services. Published GDP shares and amounts are rounded.`:view==='receipts'?'Selected taxes plus an explicit residual to public-sector current receipts. Corporation tax is gross of credits; the residual mixes other taxes, non-tax revenue and accounting differences. Current receipts are not the tax burden.':'Categories plus explicit residual reconcile to total managed expenditure. Net social benefits include pensions; goods and services span health, education and other services. Interest includes dividends paid externally and is not net debt interest. Economic categories and functions are alternative breakdowns: do not add them together.';
 const interestBridge=(year:BudgetYear)=>{const endpoint=`${Number(year.year.slice(0,4))+1}-03`,gdp=gdpAt(fiscal.gdp,endpoint)?.rollingAnnualMillion;const paid=total(fiscal.observations,'interest',endpoint,'ytd'),received=total(fiscal.observations,'interestReceipts',endpoint,'ytd');return {paid:paid!=null&&gdp?paid/gdp*100:null,received:received!=null&&gdp?received/gdp*100:null,net:paid!=null&&received!=null&&gdp?(paid-received)/gdp*100:null};};
 const aInterest=first?interestBridge(first):null,bInterest=last?interestBridge(last):null;
 const changes=first&&last?names.map(name=>{const a=first.items.find(i=>i.name===name),b=last.items.find(i=>i.name===name);return {name,a:a?.pctGdp??null,b:b?.pctGdp??null,delta:a?.pctGdp!=null&&b?.pctGdp!=null?b.pctGdp-a.pctGdp:null};}).sort((a,b)=>Math.abs(b.delta||0)-Math.abs(a.delta||0)):[];
 const comparisonHeaders=['Category',`${first?.year} (% GDP)`,`${last?.year} (% GDP)`,'Change (percentage points)'];
 const comparisonRows=changes.map(c=>[c.name,c.a,c.b,c.delta]);
 if(first&&last)comparisonRows.push(['Total',first.totalPctGdp,last.totalPctGdp,first.totalPctGdp!=null&&last.totalPctGdp!=null?last.totalPctGdp-first.totalPctGdp:null]);
 const select=(label:string,value:string,onChange:(v:string)=>void,options:{value:string;label:string}[])=><label className="select-label"><span>{label}</span><select aria-label={label} value={value} onChange={e=>onChange(e.target.value)}>{options.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select></label>;
 const taxRows:ChartRow[]=fiscal.observations.filter(r=>r.date.endsWith('-03')).flatMap(r=>{const taxes=total(fiscal.observations,'totalTaxes',r.date,'ytd'),receipts=total(fiscal.observations,'receipts',r.date,'ytd'),gdp=gdpAt(fiscal.gdp,r.date);return taxes!=null&&receipts!=null&&gdp?[{label:`${Number(r.date.slice(0,4))-1}-${r.date.slice(2,4)}`,taxes:taxes/gdp.rollingAnnualMillion!*100,receipts:receipts/gdp.rollingAnnualMillion!*100}]:[];});
 return <Disclosure open={new URLSearchParams(location.search).get('budget')==='history'} title="Compare budgets over time" subtitle="Full financial years · spending composition, tax receipts and contributions to the change">
 <p className="small">Compare full April–March years to avoid seasonal or partial-year effects. A plateau is not necessarily a steady state: both spending decisions and GDP growth affect these shares.</p>
 <div className="pricing-controls">{select('Budget breakdown',view,setView,[{value:'economic',label:'Spending: economic categories'},{value:'functional',label:'Spending: functions'},{value:'receipts',label:'Revenue sources'}])}{select('Budget history units',units,setUnits,[{value:'gdp',label:'% of GDP'},{value:'share',label:'% of total'},{value:'bn',label:'£bn'}])}</div>
 {first&&last?<><ChartPanel id="budget-history" title={title} subtitle={`Complete financial years · ${unit}`} summary={view==='functional'?'Health, social protection, education and other functions on a single Treasury publication vintage.':'A reconciled annual breakdown: each bar shows the composition of the total.'} rows={rows} lines={names.map((name,i)=>({key:`v${i}`,label:name,colour:palette[i%palette.length]}))} bars unit={unit} sources={sources} note={`${note} ${view==='functional'?'':`Annual % GDP uses published BKTL nominal GDP for the same April–March year, latest available GDP vintage. Fiscal vintage ${fiscal.releaseDate}. Shares of total use the named spending/receipts denominator.`}`}/>
 <div className="pricing-controls">{select('Budget comparison start',first.year,setFrom,years.map(y=>({value:y.year,label:y.year})))}{select('Budget comparison end',last.year,setTo,years.map(y=>({value:y.year,label:y.year})))}</div>
 <h3>What changed between {first.year} and {last.year}?</h3><p className="small">Changes in percentage points of GDP, ranked by absolute contribution. These are accounting contributions, not a causal estimate of any one policy.</p>
 <DataTable caption="Budget change contributions" headers={comparisonHeaders} rows={comparisonRows.map(r=>r.map(v=>typeof v==='number'?fmt(v,2):v??'Not available'))}/>
 <button onClick={()=>downloadCsv('budget-change-contributions',comparisonHeaders,comparisonRows,`${first.year} to ${last.year}. ${note} ${sources.map(s=>s.url).join(' ')}`)}>Download comparison CSV</button>
 {view==='economic'&&aInterest&&bInterest&&<><h3>Interest paid versus interest received</h3><p className="small">An analytical bridge using public-sector interest and dividends paid to, and received from, the private sector and rest of the world (ONS JW2P and JW2L). Includes dividends: this is not a pure net-debt-interest or official primary-spending measure.</p><DataTable caption="Interest and dividend bridge" headers={['% of GDP',first.year,last.year]} rows={[["Total managed expenditure",fmt(first.totalPctGdp,2),fmt(last.totalPctGdp,2)],["Interest & dividends paid",fmt(aInterest.paid,2),fmt(bInterest.paid,2)],["Interest & dividends received",fmt(aInterest.received,2),fmt(bInterest.received,2)],["Net payments",fmt(aInterest.net,2),fmt(bInterest.net,2)],["Spending less net interest & dividends",fmt(first.totalPctGdp!=null&&aInterest.net!=null?first.totalPctGdp-aInterest.net:null,2),fmt(last.totalPctGdp!=null&&bInterest.net!=null?last.totalPctGdp-bInterest.net:null,2)]]}/></>}
 {view==='functional'&&<><p className="small">Debt interest (already inside general public services): {fmt(first.debtInterestPctGdp)}% → {fmt(last.debtInterestPctGdp)}% of GDP. Do not add it again to the category total.</p><DataTable caption="TES to total spending bridge" headers={['Measure',first.year,last.year]} rows={[["Expenditure on services (% GDP)",fmt(first.totalPctGdp),fmt(last.totalPctGdp)],["Accounting adjustments (% GDP)",fmt(first.accountingAdjustmentsPctGdp),fmt(last.accountingAdjustmentsPctGdp)],["Total managed expenditure (% GDP)",fmt(first.tmePctGdp),fmt(last.tmePctGdp)]]}/><ul className="notes-list">{functional?.notes.map(n=><li key={n}>{n}</li>)}</ul></>}
 </>:<p className="notice">This breakdown is not available in the saved snapshot. Reload saved data after refreshing its source.</p>}
 <ChartPanel id="tax-take" title="Tax take versus total receipts" subtitle="Full financial years · % of GDP" summary="Taxes and NICs are only part of public-sector current receipts. Keep the two measures separate when discussing the size of the tax burden." rows={taxRows} lines={[{key:'taxes',label:'Public sector taxes & NICs'},{key:'receipts',label:'All current receipts',colour:'#b47936'}]} unit="% of GDP" sources={[...fiscal.sources,...(fiscal.gdp?.sources||[])]} note={`ONS AHHY and JW2O, divided by nominal GDP for the corresponding April–March year. Latest fiscal vintage ${dateLabel(fiscal.releaseDate)}. This is dashboard scaling, not the OBR forecast tax-burden series.`}/>
 </Disclosure>;
}
