import {useParam} from './urlState';
import {ChartPanel,DataTable,Disclosure,SourceLine,type ChartRow} from './components';
import {annualBudgets,exactAnnualGdp,budgetValue,budgetComparison,type BudgetYear,type FunctionalHistory} from './budgetMath';
import {dateLabel,downloadCsv,fmt,total,type Fiscal,type Source,type Composition} from './data';

import {budgetColours} from './chartColours';
export function BudgetHistory({fiscal,functional,composition}:{fiscal:Fiscal;functional?:FunctionalHistory;composition?:Composition}){
 const [view,setView]=useParam('bhDataset','economic');const [units,setUnits]=useParam('units','gdp');const [from,setFrom]=useParam('bhFrom','2019-20');const [to,setTo]=useParam('bhTo','');const [mode,setMode]=useParam('bhMode','snapshot');const [selection,setSelection]=useParam('bhCategories','');
 const detailed:BudgetYear[]=(composition?.years||[]).map(y=>{const gdp=exactAnnualGdp(fiscal,`${Number(y.year.slice(0,4))+1}-03`);return {...y,totalPctGdp:gdp?y.total/gdp*100:null,items:y.items.map(i=>({...i,pctGdp:gdp?i.value/gdp*100:null}))};});
 const isFunctional=view==='functional'||view==='detailed';
 const years:BudgetYear[]=view==='detailed'?detailed:view==='functional'?(functional?.years||[]):annualBudgets(fiscal,view==='receipts'?'receipts':'economic');
 const availableYears=years.filter(y=>units!=='gdp'||y.totalPctGdp!=null);
 const first=availableYears.find(y=>y.year===from)||availableYears[0],last=availableYears.find(y=>y.year===to)||availableYears.at(-1);
 const sources:Source[]=isFunctional?(view==='detailed'?composition?.sources||[]:functional?.sources||[]):[...fiscal.sources,...(fiscal.gdp?.sources||[])];
 const totalName=isFunctional?'expenditure on services':view==='receipts'?'current receipts':'total managed expenditure';
 const unit=units==='gdp'?'% of GDP':units==='share'?`% of ${totalName}`:'£bn';
 const deltaUnit=units==='gdp'?'percentage points of GDP':units==='share'?`percentage points of ${totalName}`:'£bn';
 const title=view==='receipts'?'Revenue composition over time':isFunctional?'Spending by function over time':'Spending by economic category over time';
 const names=[...new Set(years.flatMap(y=>y.items.map(i=>i.name)))];
 const selected=selection?selection.split('|').filter(n=>names.includes(n)):[...(last?.items||[])].sort((a,b)=>b.value-a.value).slice(0,3).map(i=>i.name);
 const rows:ChartRow[]=years.map(y=>({label:y.year,total:budgetValue(y.total,y.totalPctGdp,y.total,units),...Object.fromEntries(names.map((name,i)=>{const item=y.items.find(x=>x.name===name);return [`v${i}`,item?budgetValue(item.value,item.pctGdp,y.total,units):null];}))}));
 const note=isFunctional?`${view==='detailed'?composition?.basis:functional?.basis}. Categories sum to expenditure on services (TES), not total managed expenditure (TME). Social protection includes pensions and social services; it is not just working-age benefits. Debt interest is included within general public services. ${view==='detailed'?'Detailed amounts are published in £ million; GDP shares use matching full-year ONS GDP. This five-year view is kept separate from the rounded historical series.':'Published GDP shares and amounts are rounded.'}`:view==='receipts'?'Selected taxes plus an explicit residual to public-sector current receipts. Corporation tax is gross of credits; the residual mixes other taxes, non-tax revenue and accounting differences. Current receipts are not the tax burden.':'Categories plus explicit residual reconcile to total managed expenditure. Net social benefits include pensions; goods and services span health, education and other services. Interest includes dividends paid externally and is not net debt interest. Economic categories and functions are alternative breakdowns: do not add them together.';
 const interestBridge=(year:BudgetYear)=>{const endpoint=`${Number(year.year.slice(0,4))+1}-03`,gdp=exactAnnualGdp(fiscal,endpoint);const paid=total(fiscal.observations,'interest',endpoint,'ytd'),received=total(fiscal.observations,'interestReceipts',endpoint,'ytd');return {paid:paid!=null&&gdp?paid/gdp*100:null,received:received!=null&&gdp?received/gdp*100:null,net:paid!=null&&received!=null&&gdp?(paid-received)/gdp*100:null};};
 const aInterest=first?interestBridge(first):null,bInterest=last?interestBridge(last):null;
 const snapshot=last?[...last.items].map(i=>({...i,display:budgetValue(i.value,i.pctGdp,last.total,units)})).sort((a,b)=>(b.display??0)-(a.display??0)):[];
 const snapshotMax=Math.max(1,...snapshot.map(i=>Math.abs(i.display??0)));
 const comparison=first&&last?budgetComparison(first,last,units):null;
 const comparisonHeaders=['Category',`${first?.year} (${unit})`,`${last?.year} (${unit})`,`Change (${deltaUnit})`];
 const comparisonRows:(string|number|null)[][]=comparison?comparison.rows.map(c=>[c.name,c.start,c.end,c.change]):[];
 if(comparison){if(comparison.residual!=null&&Math.abs(comparison.residual)>1e-8)comparisonRows.push(['Unallocated / rounding difference',null,null,comparison.residual]);comparisonRows.push([totalName,comparison.start,comparison.end,comparison.change]);}
 const select=(label:string,value:string,onChange:(v:string)=>void,options:{value:string;label:string}[])=><label className="select-label"><span>{label}</span><select aria-label={label} value={value} onChange={e=>onChange(e.target.value)}>{options.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select></label>;
 const taxRows:ChartRow[]=fiscal.observations.filter(r=>r.date.endsWith('-03')).flatMap(r=>{const taxes=total(fiscal.observations,'totalTaxes',r.date,'ytd'),receipts=total(fiscal.observations,'receipts',r.date,'ytd'),gdp=exactAnnualGdp(fiscal,r.date);return taxes!=null&&receipts!=null&&gdp?[{label:`${Number(r.date.slice(0,4))-1}-${r.date.slice(2,4)}`,taxes:budgetValue(taxes,taxes/gdp*100,receipts,units),receipts:budgetValue(receipts,receipts/gdp*100,receipts,units)}]:[];});
 return <section aria-label="Budget composition"><div className="page-heading"><div><p className="eyebrow">SPENDING AND RECEIPTS</p><h1>Spending and revenue composition</h1><p className="intro">What the budget funds, how it is financed, and how both have changed.</p></div></div>
 {new URLSearchParams(location.search).has('bhFrom')&&from&&!availableYears.some(y=>y.year===from)&&<p className="notice">Requested comparison start {from} is unavailable for this breakdown and unit.{first?` Showing ${first.year} instead; select another available year to change the comparison.`:' No comparable year is available.'}</p>}
 {to&&!availableYears.some(y=>y.year===to)&&<p className="notice">Requested financial year {to} is unavailable for this breakdown and unit.{last?` Showing ${last.year} instead; select another available year to change the view.`:' No comparable year is available.'}</p>}
 <p className="small">Compare full April–March years to avoid seasonal or partial-year effects. A plateau is not necessarily a steady state: both spending decisions and GDP growth affect these shares.</p>
 <div className="pricing-controls">{select('Budget breakdown',view,setView,[{value:'economic',label:'Spending: economic categories'},{value:'functional',label:'Spending: functions (long history)'},...(composition?[{value:'detailed',label:'Spending: functions (detailed amounts, 5 years)'}]:[]),{value:'receipts',label:'Revenue sources'}])}{select('Budget history units',units,setUnits,[{value:'gdp',label:'% of GDP'},{value:'share',label:`% of ${totalName}`},{value:'bn',label:'£bn'}])}</div>
 <div className="data-nav" aria-label="Composition views">{[['snapshot','Composition'],['history','Over time'],['change','Change between years']].map(([key,label])=><button key={key} aria-pressed={mode===key} onClick={()=>setMode(key)}>{label}</button>)}</div>
 {first&&last?<>
 {mode==='snapshot'&&<><div className="pricing-controls">{select('Composition financial year',last.year,setTo,availableYears.map(y=>({value:y.year,label:y.year})))}</div><section className="panel"><h2>{view==='receipts'?'Revenue sources':isFunctional?'Spending by function':'Spending by economic category'} · {last.year}</h2><p>{totalName}: {fmt(budgetValue(last.total,last.totalPctGdp,last.total,units),2)} {unit}</p><p className="small">Ranked largest first. Complete April–March financial year{last.year===availableYears.at(-1)?.year?' · latest complete year':''}. {units==='gdp'?'Values are shares of GDP.':units==='share'?`Denominator: ${totalName}.`:'Values are nominal £bn.'}</p><p className="small">Bar length shows magnitude: 0 to {fmt(snapshotMax,2)} {unit}. Negative residuals are labelled with a minus sign.</p><ul className="bar-list">{snapshot.map(i=><li key={i.name}><div className="bar-label"><span>{i.name}</span><span>{fmt(i.display,2)} {unit}</span></div><div className="bar-track" aria-hidden="true"><div className={i.display!=null&&i.display<0?'negative':''} style={{width:`${Math.abs(i.display??0)/snapshotMax*100}%`,backgroundColor:budgetColours[i.name]||'#64748B'}}/></div></li>)}</ul><button onClick={()=>downloadCsv('budget-composition',['Category',unit],last.items.map(i=>[i.name,budgetValue(i.value,i.pctGdp,last.total,units)]),`${last.year}. ${note} ${sources.map(s=>s.url).join(' ')}`)}>Download composition CSV</button><SourceLine sources={sources} note={note}/></section></>}
 {mode==='history'&&<><fieldset><legend>Highlight categories</legend><p className="small">The named total stays visible. Select categories to compare without stacking overlapping classifications.</p>{names.map(name=><label key={name} style={{display:'inline-flex',gap:6,margin:'6px 16px 6px 0'}}><input type="checkbox" checked={selected.includes(name)} onChange={()=>setSelection((selected.includes(name)?selected.filter(n=>n!==name):[...selected,name]).join('|')||'none')}/>{name}</label>)}</fieldset><ChartPanel id="budget-history" title={title} subtitle={`Complete financial years · ${unit}`} summary="Full comparable history. Highlight individual categories against the named total; gaps remain missing." rows={rows} lines={[{key:'total',label:totalName,colour:'#253d36',dash:'5 3'},...names.flatMap((name,i)=>selected.includes(name)?[{key:`v${i}`,label:name,colour:budgetColours[name]||'#64748B'}]:[])]} xLabel="Financial year (April–March)" unit={unit} sources={sources} note={note}/></>}
 {mode==='change'&&<><div className="pricing-controls">{select('Budget comparison start',first.year,setFrom,availableYears.map(y=>({value:y.year,label:y.year})))}{select('Budget comparison end',last.year,setTo,availableYears.map(y=>({value:y.year,label:y.year})))}<button onClick={()=>setFrom(availableYears[Math.max(0,availableYears.findIndex(y=>y.year===last.year)-1)].year)}>Previous year</button>{availableYears.some(y=>y.year==='2019-20')&&<button onClick={()=>setFrom('2019-20')}>Pre-pandemic reference (2019–20)</button>}</div>
 <h2>What changed between {first.year} and {last.year}?</h2><p className="small">Changes in {deltaUnit}, ranked by absolute contribution. These are accounting contributions, not a causal estimate of any one policy. {units==='share'?'Shares of the named total sum to 100%; their changes sum to zero, apart from rounding.':'Category contributions reconcile to the change in the named total.'}</p>
 <DataTable caption="Budget change contributions" headers={comparisonHeaders} rows={comparisonRows.map(r=>r.map(v=>typeof v==='number'?fmt(v,2):v??'Not available'))}/>
 {comparison?.residual==null&&<p className="notice">Some categories are missing in one of the selected years. The available contributions cannot be reconciled; missing values are not treated as zero.</p>}
 <button onClick={()=>downloadCsv('budget-change-contributions',comparisonHeaders,comparisonRows,`${first.year} to ${last.year}. ${note} ${sources.map(s=>s.url).join(' ')}`)}>Download comparison CSV</button><SourceLine sources={sources} note={note}/></>}
 <Disclosure title="Accounting boundaries and supporting measures" subtitle="Interest bridge, functional spending adjustments and tax definitions">
 {view==='economic'&&aInterest&&bInterest&&<><h3>Interest paid versus interest received</h3><p className="small">An analytical bridge using public-sector interest and dividends paid to, and received from, the private sector and rest of the world (ONS JW2P and JW2L). Includes dividends: this is not a pure net-debt-interest or official primary-spending measure.</p><DataTable caption="Interest and dividend bridge" headers={['% of GDP',first.year,last.year]} rows={[["Total managed expenditure",fmt(first.totalPctGdp,2),fmt(last.totalPctGdp,2)],["Interest & dividends paid",fmt(aInterest.paid,2),fmt(bInterest.paid,2)],["Interest & dividends received",fmt(aInterest.received,2),fmt(bInterest.received,2)],["Net payments",fmt(aInterest.net,2),fmt(bInterest.net,2)],["Spending less net interest & dividends",fmt(first.totalPctGdp!=null&&aInterest.net!=null?first.totalPctGdp-aInterest.net:null,2),fmt(last.totalPctGdp!=null&&bInterest.net!=null?last.totalPctGdp-bInterest.net:null,2)]]}/></>}
 {view==='functional'&&<><p className="small">Debt interest (already inside general public services): {fmt(first.debtInterestPctGdp)}% → {fmt(last.debtInterestPctGdp)}% of GDP. Do not add it again to the category total.</p><DataTable caption="TES to total spending bridge" headers={['Measure',first.year,last.year]} rows={[["Expenditure on services (% GDP)",fmt(first.totalPctGdp),fmt(last.totalPctGdp)],["Accounting adjustments (% GDP)",fmt(first.accountingAdjustmentsPctGdp),fmt(last.accountingAdjustmentsPctGdp)],["Total managed expenditure (% GDP)",fmt(first.tmePctGdp),fmt(last.tmePctGdp)]]}/><ul className="notes-list">{functional?.notes.map(n=><li key={n}>{n}</li>)}</ul></>}
 </Disclosure></>:<p className="notice">This breakdown is not available in the saved snapshot. Reload saved data after refreshing its source.</p>}
 {view==='receipts'&&<ChartPanel id="tax-take" title="Tax take versus total receipts" subtitle={`Full financial years · ${unit}`} summary="Taxes and NICs are only part of public-sector current receipts. Keep the two measures separate when discussing the size of the tax burden." rows={taxRows} xLabel="Financial year (April–March)" lines={[{key:'taxes',label:'Public sector taxes & NICs'},{key:'receipts',label:'All current receipts',colour:'#b47936'}]} unit={unit} sources={[...fiscal.sources,...(fiscal.gdp?.sources||[])]} note={`ONS AHHY and JW2O, Scaled by nominal GDP for the corresponding April–March year, current receipts, or shown in £bn according to the selected units. Latest fiscal vintage ${dateLabel(fiscal.releaseDate)}. This is dashboard scaling, not the OBR forecast tax-burden series.`}/> }
 </section>;
}
