import {useRef,useState,type ReactNode} from 'react';
import {Download,Table2,ChevronDown,ArrowUpRight,ImageDown} from 'lucide-react';
import {ResponsiveContainer,LineChart,Line,CartesianGrid,XAxis,YAxis,Tooltip,ReferenceLine,BarChart,Bar} from 'recharts';
import {downloadCsv,fmt,type Source} from './data';

export const colours=['#17685a','#b47936','#829097','#7285a6'];
export type ChartRow=Record<string,string|number|null>;
export type LineSpec={key:string;label:string;colour?:string;dash?:string};

export function SourceLine({sources,note}:{sources:Source[];note?:string}){return <div className="source-line"><span>Source: </span>{sources.map((s,i)=><span key={s.id}>{i>0?' · ':''}<a href={s.url} target="_blank" rel="noreferrer">{s.name||s.title||s.publisher||s.id}<ArrowUpRight size={12}/></a></span>)}{sources.filter(s=>s.attribution).map(s=><span className="source-note" key={`${s.id}-attribution`}>{s.attribution}</span>)}{note&&<span className="source-note">{note}</span>}</div>;}
export function Card({label,value,detail,highlight=false}:{label:string;value:string;detail:string;highlight?:boolean}){return <article className={`metric ${highlight?'metric-primary':''}`}><h2>{label}</h2><p className="metric-value">{value}</p><p className="metric-detail">{detail}</p></article>;}
export function Disclosure({title,subtitle,children,open=false}:{title:string;subtitle?:string;children:ReactNode;open?:boolean}){return <details className="disclosure" open={open||undefined}><summary><span><span className="disclosure-title">{title}</span>{subtitle&&<span className="disclosure-subtitle">{subtitle}</span>}</span><ChevronDown size={20}/></summary><div className="disclosure-body">{children}</div></details>;}
export function DataTable({caption,headers,rows}:{caption:string;headers:string[];rows:(ReactNode)[][]}){return <><p className="table-hint">Scroll the table horizontally for additional columns.</p><div className="table-wrap" role="region" aria-label={caption} tabIndex={0}><table><caption className="sr-only">{caption}</caption><thead><tr>{headers.map((h,i)=><th key={i} scope="col">{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((v,j)=><td key={j}>{v??'—'}</td>)}</tr>)}</tbody></table></div></>;}

export function ChartPanel({id,title,subtitle,summary,rows,lines,xKey='label',xLabel,extraColumns=[],unit='£bn',sources,note,children,bars=false,zero=true}:{id:string;title:string;subtitle?:string;summary:string;rows:ChartRow[];lines:LineSpec[];xKey?:string;xLabel?:string;extraColumns?:{key:string;label:string}[];unit?:string;sources:Source[];note?:string;children?:ReactNode;bars?:boolean;zero?:boolean}){
  const [table,setTable]=useState(false);const ref=useRef<HTMLElement>(null);const [exportError,setExportError]=useState('');
  const meta=`${title}. ${subtitle||''}. ${unit}. ${summary}. ${note||''}. ${sources.map(s=>`${s.name||s.title||s.id}: ${s.url}; published ${s.publicationDate||'unknown'}. ${s.attribution||''}`).join('; ')}`;
  const headers=[xLabel||(xKey==='label'?'Period':xKey),...lines.map(l=>`${l.label} (${unit})`),...extraColumns.map(c=>c.label)];
  const csvRows=rows.map(r=>[r[xKey],...lines.map(l=>r[l.key]),...extraColumns.map(c=>r[c.key])]);
  function exportChart(){
    const svg=ref.current?.querySelector('svg.recharts-surface');if(!svg){setExportError('Show the chart before exporting.');return;}
    const clone=svg.cloneNode(true) as SVGSVGElement;const oldWidth=Number(svg.getAttribute('width'))||800;const oldHeight=Number(svg.getAttribute('height'))||300;
    const width=960;const plotHeight=Math.min(500,Math.max(300,oldHeight*width/oldWidth));
    const ns='http://www.w3.org/2000/svg';const root=document.createElementNS(ns,'svg');root.setAttribute('xmlns',ns);root.setAttribute('width',String(width));root.setAttribute('font-family','Arial, sans-serif');
    const bg=document.createElementNS(ns,'rect');bg.setAttribute('width','100%');bg.setAttribute('height','100%');bg.setAttribute('fill','#ffffff');root.append(bg);
    const description=document.createElementNS(ns,'desc');description.textContent=meta;root.append(description);
    const addText=(text:string,x:number,y:number,size=13)=>{const el=document.createElementNS(ns,'text');el.setAttribute('x',String(x));el.setAttribute('y',String(y));el.setAttribute('font-size',String(size));el.setAttribute('fill','#223f39');el.textContent=text;root.append(el);};
    let y=30;
    function wrapped(text:string,size=13){const limit=Math.floor((width-40)/(size*.56));let line='';for(const word of text.split(' ')){if((line+' '+word).length>limit){addText(line,20,y,size);y+=size+7;line=word;}else line+=(line?' ':'')+word;}addText(line,20,y,size);y+=size+9;}
    wrapped(title,23);wrapped(`${subtitle||''} · ${unit}`);
    for(const [i,line] of lines.entries()){const swatch=document.createElementNS(ns,bars?'rect':'line');if(bars){swatch.setAttribute('x','20');swatch.setAttribute('y',String(y-14));swatch.setAttribute('width','14');swatch.setAttribute('height','14');swatch.setAttribute('fill',line.colour||colours[i]);}swatch.setAttribute('x1','20');swatch.setAttribute('x2','45');swatch.setAttribute('y1',String(y-4));swatch.setAttribute('y2',String(y-4));swatch.setAttribute('stroke',line.colour||colours[i]);swatch.setAttribute('stroke-width',bars?'0':'3');if(line.dash)swatch.setAttribute('stroke-dasharray',line.dash);root.append(swatch);addText(line.label,55,y);y+=22;}
    clone.setAttribute('x','15');clone.setAttribute('y',String(y));clone.setAttribute('width',String(width-30));clone.setAttribute('height',String(plotHeight));clone.setAttribute('viewBox',`0 0 ${oldWidth} ${oldHeight}`);clone.setAttribute('preserveAspectRatio','none');root.append(clone);y+=plotHeight+24;
    wrapped(sources.map(s=>`${s.name||s.title||s.id} (published ${s.publicationDate||'unknown'}). ${s.attribution||''}`).join('; '),12);wrapped(note||summary,12);
    root.setAttribute('height',String(y+12));root.setAttribute('viewBox',`0 0 ${width} ${y+12}`);
    const url=URL.createObjectURL(new Blob([new XMLSerializer().serializeToString(root)],{type:'image/svg+xml'}));const a=document.createElement('a');a.href=url;a.download=`uk-fiscal-${id}.svg`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setExportError('');
  }
  return <section className="panel chart-panel" ref={ref} aria-labelledby={`${id}-title`}><div className="panel-heading"><div><h2 id={`${id}-title`}>{title}</h2>{subtitle&&<p>{subtitle}</p>}</div><div className="chart-actions"><button aria-label={`Download ${title} CSV`} title="Download CSV" onClick={()=>downloadCsv(id,headers,csvRows,meta)}><Download size={16}/><span>CSV</span></button><button aria-label={`Download ${title} SVG`} title="Download chart" onClick={exportChart}><ImageDown size={16}/></button><button aria-label={`${table?'Show chart':'Show data table'} for ${title}`} aria-pressed={table} title="Toggle data table" onClick={()=>setTable(!table)}><Table2 size={16}/></button></div></div>{children}<p className="chart-summary">{summary}</p><div className={`legend ${bars?'legend-bars':''}`}>{lines.map((l,i)=><span key={l.key}><i style={bars?{backgroundColor:l.colour||colours[i]}:{borderColor:l.colour||colours[i],borderStyle:l.dash?'dashed':'solid'}}/>{l.label}</span>)}</div>{exportError&&<p role="status">{exportError}</p>}
    {table?<DataTable caption={title} headers={headers} rows={csvRows.map(r=>r.map(v=>typeof v==='number'?fmt(v,2):v??'Not available'))}/>:<div className="chart" role="img" aria-label={`${title}. ${summary} Use the data table button for all values.`}><ResponsiveContainer width="100%" height="100%">{bars?<BarChart stackOffset="sign" data={rows} margin={{top:16,right:12,left:-12,bottom:xLabel?24:4}}><CartesianGrid stroke="#e5e9e5" vertical={false}/><XAxis dataKey={xKey} type={xKey==='tenor'?'number':'category'} domain={xKey==='tenor'?['dataMin','dataMax']:undefined} tick={{fontSize:12,fill:'#5a6a65'}} tickLine={false} axisLine={false} minTickGap={28} label={xLabel?{value:xLabel,position:'insideBottom',offset:-18,fill:'#53665c',fontSize:12}:undefined}/><YAxis tick={{fontSize:12,fill:'#5a6a65'}} tickLine={false} axisLine={false}/><Tooltip itemStyle={{color:'#253d36'}} formatter={(v)=>`${fmt(Number(v),2)} ${unit}`} contentStyle={{borderRadius:8,fontSize:13}}/><ReferenceLine y={0} stroke="#cbd4cd"/>{lines.map((l,i)=><Bar key={l.key} dataKey={l.key} name={l.label} fill={l.colour||colours[i]} stackId="stock" stroke="#ffffff" strokeWidth={0.65} isAnimationActive={false}/>)}</BarChart>:<LineChart data={rows} margin={{top:16,right:16,left:-12,bottom:xLabel?24:4}}><CartesianGrid stroke="#e5e9e5" vertical={false}/><XAxis dataKey={xKey} type={xKey==='tenor'?'number':'category'} domain={xKey==='tenor'?['dataMin','dataMax']:undefined} tick={{fontSize:12,fill:'#5a6a65'}} tickLine={false} axisLine={false} minTickGap={28} label={xLabel?{value:xLabel,position:'insideBottom',offset:-18,fill:'#53665c',fontSize:12}:undefined}/><YAxis domain={zero?['auto','auto']:['dataMin - 0.15','dataMax + 0.15']} tick={{fontSize:12,fill:'#5a6a65'}} tickFormatter={v=>fmt(v,unit.includes('%')||unit==='bp'||Math.abs(v)<10?1:0)} tickLine={false} axisLine={false}/><Tooltip itemStyle={{color:'#253d36'}} formatter={(v)=>`${fmt(Number(v),2)} ${unit}`} contentStyle={{borderRadius:8,fontSize:13}}/>{zero&&<ReferenceLine y={0} stroke="#cbd4cd"/>}{lines.map((l,i)=><Line key={l.key} type="linear" dataKey={l.key} name={l.label} stroke={l.colour||colours[i]} strokeWidth={l.dash?2:2.5} strokeDasharray={l.dash} dot={false} activeDot={{r:4}} isAnimationActive={false} connectNulls={false}/>)}</LineChart>}</ResponsiveContainer></div>}
    <SourceLine sources={sources} note={note}/></section>;
}

export function CompositionBars({title,items,total,source,metadata,units='share',gdp=null,totalName='Named total',gdpNote=''}:{title:string;items:{name:string;value:number}[];total:number;source:Source[];metadata:string;units?:'share'|'gdp';gdp?:number|null;totalName?:string;gdpNote?:string}){
 const sorted=[...items].sort((a,b)=>b.value-a.value);const denominator=units==='gdp'?gdp:total;
 const valid=denominator!=null&&Number.isFinite(denominator)&&denominator>0;
 const share=(value:number)=>valid?value/denominator!*100:null;
 const shareLabel=units==='gdp'?'Share of GDP (%)':'Share of named total (%)';
 const definition=units==='gdp'?`Denominator: ${gdpNote}. ${gdp!=null?`Nominal GDP £${fmt(gdp/1000)}bn.`:'GDP unavailable; percentages are not estimated.'}`:`Denominator: ${totalName}, £${fmt(total/1000)}bn.`;
 const meta=`${metadata} Display: ${shareLabel}. ${definition}`;
 return <section className="composition-block"><div className="panel-heading"><h3>{title}</h3><button className="plain-button" onClick={()=>downloadCsv(title.toLowerCase().replaceAll(' ','-'),['Category','£ million',shareLabel,'Denominator (£ million)'],sorted.map(x=>[x.name,x.value,share(x.value),valid?denominator:null]),meta)} aria-label={`Download ${title} CSV`}><Download size={15}/> CSV</button></div><p className="small">{totalName}: £{fmt(total/1000)}bn</p><p className="small">{definition} Bars use a 0–100% scale.</p><ul className="bar-list">{sorted.map(x=><li key={x.name}><div className="bar-label"><span>{x.name}</span><span>£{fmt(x.value/1000)}bn <small>{share(x.value)==null?'N/A':`${fmt(share(x.value))}%`}</small></span></div><div className="bar-track"><div className={x.value<0?'negative':''} style={{width:`${Math.min(100,Math.abs(share(x.value)||0))}%`}}/></div></li>)}</ul><SourceLine sources={source} note={meta}/></section>;
}
