import {ChartPanel,DataTable,Disclosure} from './components';
import {fmt,type Bundle} from './data';
import {latestVintage} from './policyData';
import {deficitParts,deficitHistoryRows} from './deficitMath';
import {useParam,ViewLink} from './urlState';

export function Deficits({bundle,compact=false}:{bundle:Bundle;compact?:boolean}){
 const outlook=bundle.policy?.outlook;const [selected,setSelected]=useParam('vintage','');const [rawUnits,setUnits]=useParam('units','gdp');const units=rawUnits==='bn'?'bn':'gdp';const unit=units==='bn'?'£bn':'% of GDP';
 const [historyRange,setHistoryRange]=useParam('deficitHistory','2000');const [display,setDisplay]=useParam('deficitDisplay','components');
 const vintage=outlook?.vintages.find(v=>v.id===selected)||latestVintage(outlook||null);
 if(!vintage)return <section><h2>Deficit decomposition</h2><p className="notice">The OBR decomposition is unavailable in the saved snapshot.</p></section>;
 const start=historyRange==='all'?'1990':historyRange==='recent'?'2015':'2000';
 const rows=deficitHistoryRows(outlook?.history||[],vintage.rows,start).map(r=>({label:r.year+(r.year>=vintage.forecastStart?' (F)':''),...deficitParts(r,units),status:r.year>=vintage.forecastStart?'Forecast':r.year<vintage.rows[0].year?'Historical outturn · total only':'Outturn / estimate'}));
 const parts=rows.flatMap(r=>[[r.primary,r.interest],[r.structural,r.cyclical]]).filter(p=>p.every(v=>v!=null));const yDomain:[number,number]=[Math.floor(Math.min(0,...rows.map(r=>r.total??0),...parts.map(p=>p.reduce<number>((s,v)=>s+Math.min(0,v!),0)))),Math.ceil(Math.max(1,...rows.map(r=>r.total??0),...parts.map(p=>p.reduce<number>((s,v)=>s+Math.max(0,v!),0))))];
 const source=vintage.sources||outlook?.sources||[];
 const note=`${vintage.label}. Forecast from ${vintage.forecastStart}; earlier totals use latest ONS history, with the selected OBR vintage taking precedence from its first published year. Positive = deficit or cost; negative = surplus or offset. Ratios are calculated from source £bn amounts and matched annual GDP, so may differ from published rounded percentages. Net interest uses the OBR definition, not the ONS interest-and-dividends proxy.`;
 return <section className={compact?'overview-deficits':'editorial'} aria-labelledby={compact?'overview-deficits-title':'deficits-title'}><div className="section-heading">{compact?<h3 id="overview-deficits-title">Economic decomposition</h3>:<h1 id="deficits-title">Deficit decomposition.</h1>}{compact&&<ViewLink href="?page=fiscal&section=deficits">Definitions and primary structural balance →</ViewLink>}</div>
 <p className="small">Two views of the same borrowing total: removing net interest gives primary borrowing; removing the estimated cycle gives cyclically adjusted (“structural”) borrowing. These are alternative decompositions, not components to add together.</p>
 <div className="pricing-controls"><label className="select-label">Deficit forecast vintage<select value={vintage.id} onChange={e=>setSelected(e.target.value)}>{outlook?.vintages.map(v=><option key={v.id} value={v.id}>{v.label}</option>)}</select></label><label className="select-label">Deficit units<select value={units} onChange={e=>setUnits(e.target.value)}><option value="gdp">% of GDP</option><option value="bn">£bn</option></select></label><label className="select-label">History<select value={historyRange} onChange={e=>setHistoryRange(e.target.value)}><option value="2000">Since 2000–01</option><option value="recent">Since 2015–16</option><option value="all">All available · since 1990–91</option></select></label><label className="select-label">Deficit display<select value={display} onChange={e=>setDisplay(e.target.value)}><option value="components">Components + net total</option><option value="net">Net total only</option></select></label></div>
 <p className="small">The bold dark line shows net borrowing after offsets. Negative components sit below zero. The shaded region and lighter bars show forecasts. Before {vintage.rows[0].year} only the borrowing total is available on a comparable basis; missing components are not zero.</p>{!rows.some(r=>r.structural!=null)&&<p className="notice">Structural and cyclical borrowing are unavailable in this saved vintage; refresh the outlook data to populate the second chart.</p>}<div className="composition-grid"><ChartPanel id={`${compact?'overview-':''}deficit-primary`} title="Primary borrowing and net interest" summary={`Total borrowing = primary borrowing + net debt interest. Negative primary borrowing offsets interest. Shading and lighter bars denote forecasts from ${vintage.forecastStart}.`} rows={rows} bars showBars={display!=='net'} shadeForecast yDomain={yDomain} lines={[{key:'primary',label:'Primary borrowing',colour:'#175d65'},{key:'interest',label:'Net debt interest',colour:'#a76232'}]} overlayLine={{key:'total',label:'Net total borrowing · line',colour:'#172b35'}} extraColumns={[{key:'status',label:'Observation status'}]} xLabel="Financial year" unit={unit} sources={source} note={note}/><ChartPanel id={`${compact?'overview-':''}deficit-cycle`} title="Structural and cyclical borrowing" summary={`Total borrowing = cyclically adjusted borrowing + the cyclical component. Shading and lighter bars denote forecasts from ${vintage.forecastStart}.`} rows={rows} bars showBars={display!=='net'} shadeForecast yDomain={yDomain} lines={[{key:'structural',label:'Structural borrowing',colour:'#175d65'},{key:'cyclical',label:'Cyclical component',colour:'#7186a2'}]} overlayLine={{key:'total',label:'Net total borrowing · line',colour:'#172b35'}} extraColumns={[{key:'status',label:'Observation status'}]} xLabel="Financial year" unit={unit} sources={source} note={`${note} Structural is the OBR cyclically adjusted measure; it is model-dependent, revised, and not necessarily a discretionary-policy or permanent deficit.`}/></div>
 {!compact&&<><ChartPanel id="deficit-total" title="Total and primary borrowing" shadeForecast summary="The distance between total and primary borrowing is net debt interest. Dashed paths are forecasts." rows={rows.map((r,i)=>({...r,actual:r.status==='Forecast'?null:r.total,forecast:r.status==='Forecast'||rows[i+1]?.status==='Forecast'&&r.status!=='Forecast'?r.total:null,primaryActual:r.status==='Forecast'?null:r.primary,primaryForecast:r.status==='Forecast'||rows[i+1]?.status==='Forecast'&&r.status!=='Forecast'?r.primary:null}))} lines={[{key:'actual',label:'Total · outturn'},{key:'forecast',label:'Total · forecast',dash:'6 5'},{key:'primaryActual',label:'Primary · outturn',colour:'#a76232'},{key:'primaryForecast',label:'Primary · forecast',colour:'#a76232',dash:'6 5'}]} xLabel="Financial year" unit={unit} sources={source} note={note}/><Disclosure title="Primary structural balance and reconciliation" open><p className="small">The primary structural deficit removes both net interest and the estimated cycle. Its published GDP ratio is rounded; conversion to £bn and the residual cyclical primary component inherit that rounding. Do not infer cyclically adjusted interest by subtracting these rounded measures.</p><DataTable caption="Deficit reconciliation" headers={['Year','Status',`Total (${unit})`,`Primary (${unit})`,`Net interest (${unit})`,`Structural total (${unit})`,`Cyclical total (${unit})`,`Structural primary (${unit})`,`Cyclical primary / rounding (${unit})`]} rows={rows.map(r=>[r.label,r.status,...[r.total,r.primary,r.interest,r.structural,r.cyclical,r.structuralPrimary,r.cyclicalPrimary].map(v=>fmt(v,2))])}/></Disclosure><p className="small">Coverage is {rows[0]?.label}–{rows.at(-1)?.label} for the selected OBR vintage. Component coverage begins with the selected OBR vintage in 2024–25. Earlier comparable decompositions have not been imported; historical totals use the latest ONS data, and the ONS interest/dividends proxy is kept separate. An output gap estimate underlies cyclical adjustment; this is not a directly observed monthly split.</p></>}
 </section>;
}

export function DeficitHeadline({bundle}:{bundle:Bundle}){
 const outlook=bundle.policy?.outlook;
 const [selected]=useParam('vintage',''),[rawUnits]=useParam('units','gdp'),[historyRange]=useParam('deficitHistory','2000');
 const vintage=outlook?.vintages.find(v=>v.id===selected)||latestVintage(outlook||null);
 if(!vintage)return null;
 const units=rawUnits==='bn'?'bn':'gdp';
 const history=deficitHistoryRows(outlook?.history||[],vintage.rows,historyRange==='all'?'1990':historyRange==='recent'?'2015':'2000');
 const baseline=history.filter(r=>r.year<vintage.forecastStart).at(-1)?.year;
 const rows=history.map(r=>{const total=deficitParts(r,units).total;return {label:r.year,status:r.year>=vintage.forecastStart?'Forecast':'Outturn / estimate',actual:r.year<vintage.forecastStart?total:null,forecast:r.year>=vintage.forecastStart||r.year===baseline?total:null};});
 return <ChartPanel id="overview-path-borrowing" title="Net borrowing" summary="Spending minus receipts: positive values are deficits; negative values are surpluses. The shaded, dashed path is the forecast." rows={rows} shadeForecast lines={[{key:'actual',label:'Outturn / estimate',colour:'#172b35'},{key:'forecast',label:'OBR forecast',colour:'#172b35',dash:'6 5'}]} unit={units==='bn'?'£bn':'% of GDP'} xLabel="Financial year" sources={outlook?.sources||[]} note={`${vintage.label}. PSNB excluding public sector banks. Earlier history is latest revised ONS data; selected OBR values take precedence from ${vintage.rows[0].year}. Uses the history, units and vintage selected in the economic decomposition below.`}/>;
}
