import {ChartPanel,DataTable,Disclosure} from './components';
import {gdpAt,total,shiftMonth,type Bundle} from './data';
import {useParam,ViewLink} from './urlState';
export function SeriesExplorer({bundle}:{bundle:Bundle}){
 const [query,setQuery]=useParam('seriesQuery','','replace');const [requestedKey,setKey]=useParam('series','borrowing');const [transform,setTransform]=useParam('transform','level');const [start,setStart]=useParam('from','all');const [units,setUnits]=useParam('units','gdp');
 const fiscal=bundle.fiscal;const key=fiscal.series[requestedKey]?requestedKey:'borrowing';const stock=key==='debtPct'||key==='debtBillion';const measure=stock?'level':['level','yoy','cumulative','receipts','gdp'].includes(transform)?transform:'level';
 const monetary=measure==='level'||measure==='cumulative'||measure==='gdp';const useGdp=measure==='gdp'||units!=='bn';const unit=measure==='yoy'?'% change':measure==='receipts'?'% of receipts':monetary&&useGdp?'% GDP':'£bn';
 const effectiveKey=stock?(useGdp?'debtPct':'debtBillion'):key;const series=fiscal.series[effectiveKey];const available=fiscal.observations.filter(r=>typeof r[effectiveKey]==='number');const years=[...new Set(available.map(r=>r.date.slice(0,4)))];const selectedStart=start==='all'||years.includes(start)?start:'all';
 const rows=available.length?fiscal.observations.filter(r=>r.date>=available[0].date&&r.date<=available.at(-1)!.date&&(selectedStart==='all'||r.date>=`${selectedStart}-01`)).map(r=>{
  const raw=r[effectiveKey];let value=typeof raw==='number'?raw:null;
  if(value!=null){
   if(stock){value=typeof r[useGdp?'debtPct':'debtBillion']==='number'?r[useGdp?'debtPct':'debtBillion'] as number:null;}
   else if(measure==='yoy'){const old=fiscal.observations.find(x=>x.date===shiftMonth(r.date,-12))?.[key];value=typeof old==='number'&&old>0?(value/old-1)*100:null;}
   else if(measure==='receipts'){const receipts=r.receipts;value=typeof receipts==='number'&&receipts>0?value/receipts*100:null;}
   else {if(measure==='cumulative')value=total(fiscal.observations,key,r.date,'ytd');const denominator=gdpAt(fiscal.gdp,r.date)?.rollingAnnualMillion;value=value==null?null:useGdp?(denominator?value/denominator*100:null):value/1000;}
  }return {label:r.date,value};
 }):[];
 const options=Object.entries(fiscal.series).filter(([,s])=>`${s.label} ${s.code}`.toLowerCase().includes(query.toLowerCase()));
 return <section><h2>Find a fiscal series</h2><div className="explorer-controls">
 <label className="search-label">Search name or ONS code<input value={query} onChange={e=>setQuery(e.target.value)} type="search" placeholder="Borrowing, VAT, debt…"/></label>
 <label className="select-label">Series<select value={key} onChange={e=>setKey(e.target.value)}>{!options.some(([k])=>k===key)&&<option value={key}>{fiscal.series[key]?.label}</option>}{options.map(([k,s])=><option key={k} value={k}>{s.label} · {s.code}</option>)}</select></label>
 <label className="select-label">Transformation<select value={measure} onChange={e=>setTransform(e.target.value)}><option value="level">Level</option>{!stock&&<><option value="yoy">Year-on-year change (%)</option><option value="cumulative">Fiscal-year cumulative</option><option value="receipts">Share of receipts</option>{measure==='gdp'&&<option value="gdp">Level (% GDP)</option>}</>}</select></label>
 {monetary&&<label className="select-label">Units<select value={useGdp?'gdp':'bn'} onChange={e=>{setUnits(e.target.value);if(measure==='gdp')setTransform('level');}}><option value="gdp">% GDP</option><option value="bn">£bn</option></select></label>}
 <label className="select-label">From year<select value={selectedStart} onChange={e=>setStart(e.target.value)}><option value="all">All available</option>{years.map(y=><option key={y}>{y}</option>)}</select></label></div>
 <p className="small">Available source observations: {available[0]?.date||'none'} to {available.at(-1)?.date||'none'}. Gaps and unavailable transformations remain missing.</p>
 <ChartPanel id="series-explorer" title={series?.label||key} subtitle={`ONS ${series?.code} · ${measure}`} summary={measure==='yoy'?'Same-month year-on-year percentage change; unavailable where the previous value is zero or negative.':measure==='receipts'?'Monthly value divided by monthly total receipts. This is not a share of expenditure.':stock?'End-month debt stock; the GDP ratio retains the official ONS denominator.':`${measure==='cumulative'?'Flows accumulated from April; the counter resets each financial year.':'Monthly flows.'} ${useGdp?'Divided by rolling annual nominal GDP; the numerator is not annualised.':'Shown in £bn.'}`} rows={rows} lines={[{key:'value',label:series?.label||key}]} unit={unit} yLabel={unit} xLabel="Month" sources={fiscal.sources} note={`${series?.scope}. ${fiscal.basis}. Latest publication ${fiscal.releaseDate}; latest observation ${fiscal.asOf}. Current revised vintage. Source units ${series?.unit}. Real/per-capita transformations are unavailable without a matched deflator/population series.`}/>
 <p className="small">For forecast differences use <ViewLink href="?page=fiscal&section=position">OBR profile tracking</ViewLink>; for shares of expenditure and receipts use <ViewLink href="?page=fiscal&section=composition">Budget composition</ViewLink>.</p>
 <Disclosure title="Selected series metadata"><DataTable caption="Selected series metadata" headers={['Field','Definition']} rows={Object.entries({source:'ONS public sector finances',code:series?.code,units:series?.unit,frequency:'Monthly',seasonalAdjustment:'Not seasonally adjusted',publicationDate:fiscal.releaseDate,observationDate:fiscal.asOf,coverage:`${available[0]?.date||'none'} to ${available.at(-1)?.date||'none'}`,lastChecked:bundle.manifest?.groups.fiscal?.lastChecked||'See archived metadata',vintage:'Current revised ONS outturn',scope:series?.scope}).map(([k,v])=>[k,v])}/></Disclosure></section>;
}
const methods=[
 ['Borrowing and accounting bridge','PSNB = TME − receipts. Primary-spending residual = TME − JW2P interest/dividends paid.','ONS KX5Q, JW2O, DZLS, JW2P; £million, monthly NSA. Complete financial-year sums only. Broad JW2P is not OBR net debt interest.'],
 ['Fiscal impulse','−(cyclically adjusted primary surplusₜ − cyclically adjusted primary surplusₜ₋₁), in percentage points of GDP. Positive is expansionary.','Use adjacent years within one OBR vintage. Where OBR reports primary deficits, invert the sign to obtain a surplus first. Cyclical adjustment is an uncertain model estimate, not an identified discretionary-policy effect.'],
 ['Primary / structural balance','Primary surplus excludes the matched official net debt-interest component. Cyclically adjusted balance adjusts for the estimated economic cycle.','Use the definitions in the selected OBR tables; do not substitute the broad ONS interest/dividends-paid bridge. Show forecast periods separately.'],
 ['Cumulative borrowing surprise','Σ April-to-month actual PSNB − official cumulative OBR PSNB profile. Positive means more borrowing than planned.','Current financial year only, same sector coverage and units. Forecast vintage and ONS republication date are separate. Current revised outturn is not an archived first-release surprise. No synthetic receipts, spending or interest profiles.'],
 ['GDP conversions','£million amount / matched financial-year or rolling-four-quarter nominal GDP (£million) × 100.','ONS BKTL nominal GDP, NSA. Historical monthly ratios use the latest quarter on/before the period, at most two months carry-forward. Monthly/YTD flows are not annualised. Annual relief estimates use the exact financial-year ending-March denominator. Missing denominators stay missing. Official ONS debt ratios and OBR fiscal ratios retain their source basis.'],
 ['Revenue buoyancy','(receiptsₜ / receiptsₜ₋₁ − 1) / (nominal GDPₜ / nominal GDPₜ₋₁ − 1).','Derived from adjacent complete financial years; undefined if nominal GDP growth is zero. Sensitive to policy, composition and the cycle; not a structural tax elasticity.'],
 ['Interest burden','Interest/dividends paid / total receipts × 100.','ONS JW2P / JW2O over the same complete financial year. Broad public-sector payment concept; not government gilt coupons alone.'],
 ['Forecast borrowing bridge','−Δreceipts + Δprimary current spending + Δinvestment + Δnet interest + residual = Δborrowing.','Annual £bn, first to final forecast year in the same OBR vintage. Residual displays rounding/accounting differences. This is not an economic-versus-policy decomposition.'],
 ['Debt snowball','[(r − g)/(1 + g)] × lagged debt/GDP; primary surplus offsets this contribution.','Explainer only. A numerical result would require a matched effective interest rate, nominal GDP and debt definition, including stock-flow adjustments. Market gilt yields are not substituted for the effective rate.'],
 ['Tax-relief costs and aggregates','Official HMRC headline retained separately. Ranked estimates are filtered; time-series comparisons hold numeric multi-year coverage constant.','Costs are not recoverable revenue. Missing, negligible and withheld estimates remain null. Never add relief costs to expenditure or borrowing. Original HMRC classifications/tax heads and individual forecast statuses are preserved. Pension publications and ISA holdings retain distinct dates and definitions.'],
 ['Forecast vintages and revisions','Store successive official forecast publications, never interpolate monthly profiles or overwrite an old forecast with a newer one.','Source documents, normalized bundles, checksums and application commits are archived. Earlier forecasts reconstructed from published rounded changes must be labelled as such. Formal fiscal-rule assessments are separate from forecast-implied margins.'],
 ['Monitoring and risk channels','Curated official events; publication date and observation period retained separately.','Fiscal channels explain mechanisms, not estimated policy costings or subjective risk scores. Upcoming dates exclude expired events. No exact date is assigned to unannounced fiscal events.'],
];
export function Methodology(){return <section className="editorial"><p className="eyebrow">METHODS AND DATA NOTES</p><h1>Definitions you can inspect.</h1><p className="intro">Official observations, official forecasts and our calculations are labelled separately. Every chart provides source links, a data table and downloads where applicable.</p>{methods.map(([name,formula,note])=><Disclosure key={name} title={name}><p>{formula}</p><p className="small">{note}</p></Disclosure>)}<p><ViewLink href="https://github.com/patrickmschneider/fiscal-space/tree/main/pipeline">Source adapters and validation ↗</ViewLink> · <ViewLink href="https://github.com/patrickmschneider/fiscal-space/tree/data-history">Archived releases ↗</ViewLink></p></section>;}
export function DerivedSeries({bundle}:{bundle:Bundle}){const f=bundle.fiscal;const rows=f.observations.filter(r=>r.date.endsWith('-03')).map(r=>{const receipts=total(f.observations,'receipts',r.date,'ytd'),previous=total(f.observations,'receipts',shiftMonth(r.date,-12),'ytd');const gdp=gdpAt(f.gdp,r.date)?.rollingAnnualMillion,oldGdp=gdpAt(f.gdp,shiftMonth(r.date,-12))?.rollingAnnualMillion;const growth=gdp&&oldGdp?gdp/oldGdp-1:null;const interest=total(f.observations,'interest',r.date,'ytd');return {label:`${Number(r.date.slice(0,4))-1}-${r.date.slice(2,4)}`,buoyancy:receipts!=null&&previous&&growth!=null&&Math.abs(growth)>1e-8?(receipts/previous-1)/growth:null,burden:receipts&&interest!=null?interest/receipts*100:null};});return <><ChartPanel id="revenue-buoyancy" title="How fast are receipts growing relative to nominal GDP?" summary="Revenue buoyancy is receipts growth divided by nominal GDP growth. It can be unstable when GDP growth is near zero and is not a structural tax elasticity." rows={rows} lines={[{key:'buoyancy',label:'Derived buoyancy'}]} unit="ratio" yLabel="Receipts growth / GDP growth" xLabel="Financial year" sources={f.sources} note="Adjacent complete financial years; ONS JW2O receipts and BKTL nominal GDP. Recomputed from current revised outturn."/><ChartPanel id="interest-burden" title="How much of revenue goes on interest and dividends?" summary="The broad ONS payment measure relative to total receipts, on the same financial-year basis." rows={rows} lines={[{key:'burden',label:'Interest / receipts'}]} unit="% of receipts" yLabel="Interest / receipts (%)" xLabel="Financial year" sources={f.sources} note="Derived JW2P / JW2O × 100. Not gilt coupon payments alone; not the OBR net-interest definition."/></>;}
