import {useParam,ViewLink} from './urlState';
import {annualBudgets,budgetComparison,budgetValue,type BudgetYear} from './budgetMath';
import {DataTable,Disclosure,SourceLine} from './components';
import {downloadCsv,fmt,type Bundle} from './data';

export function OverviewComposition({bundle}:{bundle:Bundle}){
 const [mode,setMode]=useParam('ocMode','snapshot');const changes=mode==='change';
 const [requestedFrom,setFrom]=useParam('ocFrom','2019-20'),[requestedTo,setTo]=useParam('ocTo','');
 const [rawUnits,setUnits]=useParam('units','gdp');const units=['gdp','bn','share'].includes(rawUnits)?rawUnits:'gdp';
 const spending:BudgetYear[]=bundle.composition.history?.years||[];
 const receipts=annualBudgets(bundle.fiscal,'receipts');
 const years=spending.filter(y=>receipts.some(r=>r.year===y.year&&(units!=='gdp'||r.totalPctGdp!=null))&&(units!=='gdp'||y.totalPctGdp!=null)).map(y=>y.year);
 const to=years.includes(requestedTo)?requestedTo:years.at(-1)||'';const from=years.includes(requestedFrom)?requestedFrom:years[0]||'';
 const unit=units==='gdp'?(changes?'pp of GDP':'% of GDP'):units==='share'?(changes?'pp of named total':'% of named total'):'£bn';
 const groups=[{name:'Spending by function',dataset:'functional',total:'Expenditure on services (TES)',years:spending,sources:[...(bundle.composition.history?.sources||[]),...(bundle.fiscal.gdp?.sources||[])],note:'TES differs from total managed expenditure above. Social protection includes pensions; general public services includes debt interest. PESA amounts and GDP shares are rounded and retain the Treasury publication’s GDP vintage. Receipt ratios use the later ONS GDP vintage, as in the full composition view.'},{name:'Receipt sources',dataset:'receipts',total:'Public-sector current receipts',years:receipts,sources:[...bundle.fiscal.sources,...(bundle.fiscal.gdp?.sources||[])],note:'Includes non-tax income. Compulsory social contributions include employer, employee and self-employed NICs. The residual also includes other taxes and accounting differences.'}].map(group=>{
  const end=group.years.find(y=>y.year===to),start=group.years.find(y=>y.year===from);const comparison=start&&end?budgetComparison(start,end,units):null;
  const rows=changes?comparison?.rows.map(r=>({name:r.name,value:r.change}))||[]:end?.items.map(i=>({name:i.name,value:budgetValue(i.value,i.pctGdp,end.total,units)}))||[];
  if(changes&&comparison?.residual!=null&&Math.abs(comparison.residual)>1e-8)rows.push({name:'Unallocated / rounding difference',value:comparison.residual});
  rows.sort((a,b)=>changes?Math.abs(b.value??0)-Math.abs(a.value??0):(b.value??0)-(a.value??0));
  return {...group,rows,aggregate:changes?comparison?.change??null:end?budgetValue(end.total,end.totalPctGdp,end.total,units):null};
 });
 const max=Math.max(0,...groups.flatMap(g=>g.rows.map(r=>Math.abs(r.value??0))))||1;
 const min=changes?-max:Math.min(0,...groups.flatMap(g=>g.rows.map(r=>r.value??0)));const extent=max-min;const zero=-min/extent*100;
 return <section className="overview-composition" aria-labelledby="overview-composition-title"><div className="section-heading"><h2 id="overview-composition-title">Spending and receipts composition</h2><ViewLink href="?page=fiscal&section=composition">Full composition history →</ViewLink></div>
 <div className="pricing-controls"><div className="segmented" aria-label="Overview composition view"><button aria-pressed={!changes} onClick={()=>setMode('snapshot')}>Composition</button><button aria-pressed={changes} onClick={()=>setMode('change')}>Change between years</button></div><label className="select-label">Composition units<select value={units} onChange={e=>setUnits(e.target.value)}><option value="gdp">% of GDP</option><option value="bn">£bn</option><option value="share">% of named total</option></select></label>{changes&&<label className="select-label">Compare from<select value={from} onChange={e=>setFrom(e.target.value)}>{years.map(y=><option key={y}>{y}</option>)}</select></label>}<label className="select-label">{changes?'Compare to':'Financial year'}<select value={to} onChange={e=>setTo(e.target.value)}>{years.map(y=><option key={y}>{y}</option>)}</select></label></div>
 <p className="small">{changes?`${from} to ${to}. Accounting contributions, not estimates of policy effects.`:`${to} · complete April–March financial year${to===years.at(-1)?' · latest common year':''}.`} {units==='share'?'Each panel uses its own named total. ':''}Shared bar scale: {fmt(min,2)} to +{fmt(max,2)} {unit}; {changes?'zero is at the centre.':'the vertical marker denotes zero.'}</p>
 {((requestedTo&&requestedTo!==to)||(changes&&requestedFrom!==from))&&<p className="notice">A requested year is unavailable on this basis. The displayed years are {changes?`${from} and `:''}{to}.</p>}
 {years.length?<div className="composition-grid">{groups.map(g=><article className="composition-ranking" key={g.dataset} aria-label={g.name}><h3>{g.name}</h3><p className="small">{g.total}{changes?' · change':''}: <strong>{fmt(g.aggregate,2)} {unit}</strong></p><ul className="bar-list">{g.rows.map(r=><li key={r.name}><div className="bar-label"><span>{r.name}</span><strong>{r.value==null?'Not available':`${changes&&r.value>0?'+':''}${fmt(r.value,2)}`}</strong></div><div className="composition-track" aria-hidden="true"><span style={{left:`${(Math.min(0,r.value??0)-min)/extent*100}%`,width:`${Math.abs(r.value??0)/extent*100}%`,background:(r.value??0)<0?'#a76232':'#175d65'}}/><i className="composition-zero" style={{left:`${zero}%`}}/></div></li>)}</ul><div className="composition-actions"><button onClick={()=>downloadCsv(`overview-${g.dataset}-${mode}`,['Category',unit],g.rows.map(r=>[r.name,r.value]),`${changes?`${from} to `:''}${to}. ${g.total}. ${g.note} ${g.sources.map(s=>s.url).join(' ')}`)}>CSV</button><ViewLink href={`?page=fiscal&section=composition&bhDataset=${g.dataset}&bhMode=${changes?'change':'history'}&bhFrom=${from}&bhTo=${to}&units=${units}`}>Explore this breakdown →</ViewLink></div><Disclosure title={`${g.name}: table and definitions`}><DataTable caption={`${g.name} composition values`} headers={['Category',unit]} rows={[...g.rows.map(r=>[r.name,fmt(r.value,2)]),[g.total,fmt(g.aggregate,2)]]}/><SourceLine sources={g.sources} note={g.note}/></Disclosure></article>)}</div>:<p className="notice">No common complete financial year is available for these datasets and units.</p>}
 <p className="small">Spending covers services (TES), whereas the top chart covers total managed expenditure (TME). The detailed view explains the accounting bridge. Accounting contributions, not estimates of policy effects. Sources: HM Treasury PESA and ONS; definitions and source links below each panel.</p>
 </section>;
}
